parameters:
  "python-sdk-folder":
    default: "C:/Users/thangle/git/azure-sdk-for-python/"
  "service-directory-name":
    default: "riskiq"

emit: [
  "@azure-tools/typespec-python",
  '@typespec/openapi3'
]

options:
  "@azure-tools/typespec-python":
    "package-mode": "dataplane"
    "package-name": "easm"
    "emitter-output-dir": "python-sdk-folder/sdk/easm/"
