# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class AssetState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """AssetState."""

    CANDIDATE = "candidate"
    CONFIRMED = "confirmed"
    DISMISSED = "dismissed"
    CANDIDATE_INVESTIGATE = "candidateInvestigate"
    ASSOCIATED_PARTNER = "associatedPartner"
    ASSOCIATED_THIRDPARTY = "associatedThirdparty"
    ARCHIVED = "archived"


class AssetUpdateState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """AssetUpdateState."""

    CANDIDATE = "candidate"
    CONFIRMED = "confirmed"
    DISMISSED = "dismissed"
    CANDIDATE_INVESTIGATE = "candidateInvestigate"
    ASSOCIATED_PARTNER = "associatedPartner"
    ASSOCIATED_THIRDPARTY = "associatedThirdparty"


class AssetUpdateTransfers(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """AssetUpdateTransfers."""

    AS = "as"
    CONTACT = "contact"
    DOMAIN = "domain"
    HOST = "host"
    IP_ADDRESS = "ipAddress"
    IP_BLOCK = "ipBlock"
    PAGE = "page"
    SSL_CERT = "sslCert"


class AuditTrailItemKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """AuditTrailItemKind."""

    AS = "as"
    CONTACT = "contact"
    DOMAIN = "domain"
    HOST = "host"
    IP_ADDRESS = "ipAddress"
    IP_BLOCK = "ipBlock"
    PAGE = "page"
    SSL_CERT = "sslCert"


class DataConnectionContent(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """DataConnectionContent."""

    ASSETS = "assets"
    ATTACK_SURFACE_INSIGHTS = "attackSurfaceInsights"


class DataConnectionFrequency(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """DataConnectionFrequency."""

    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"


class DiscoRunState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """DiscoRunState."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class DiscoSourceKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """DiscoSourceKind."""

    AS = "as"
    ATTRIBUTE = "attribute"
    CONTACT = "contact"
    DOMAIN = "domain"
    HOST = "host"
    IP_BLOCK = "ipBlock"


class ObservedPortStateValue(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ObservedPortStateValue."""

    OPEN = "open"
    CLOSED = "closed"
    FILTERED = "filtered"


class PageAssetRedirectType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """PageAssetRedirectType."""

    HTTP_HEADER = "httpHeader"
    META_REFRESH = "metaRefresh"
    JAVASCRIPT = "javascript"
    FINAL = "final"


class ReportBillableAssetBreakdownKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ReportBillableAssetBreakdownKind."""

    DOMAIN = "domain"
    HOST = "host"
    IP_ADDRESS = "ipAddress"


class SslCertAssetValidationType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """SslCertAssetValidationType."""

    DOMAIN_VALIDATION = "domainValidation"
    ORGANIZATION_VALIDATION = "organizationValidation"
    EXTENDED_VALIDATION = "extendedValidation"


class TaskPhase(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """TaskPhase."""

    RUNNING = "running"
    POLLING = "polling"
    COMPLETE = "complete"


class TaskState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """TaskState."""

    PENDING = "pending"
    RUNNING = "running"
    PAUSED = "paused"
    COMPLETE = "complete"
    INCOMPLETE = "incomplete"
    FAILED = "failed"
    WARNING = "warning"
