// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm;

public final class ReadmeSamples {
    public void readmeSamples() {
        // BEGIN: com.easm.readme
        // END: com.easm.readme
    }
}
