// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** AsAsset. */
@Immutable
public final class AsAsset {
    /*
     * The asn property.
     */
    @JsonProperty(value = "asn")
    private Long asn;

    /*
     * The asNames property.
     */
    @JsonProperty(value = "asNames")
    private List<ObservedString> asNames;

    /*
     * The orgNames property.
     */
    @JsonProperty(value = "orgNames")
    private List<ObservedString> orgNames;

    /*
     * The orgIds property.
     */
    @JsonProperty(value = "orgIds")
    private List<ObservedString> orgIds;

    /*
     * The countries property.
     */
    @JsonProperty(value = "countries")
    private List<ObservedString> countries;

    /*
     * The registries property.
     */
    @JsonProperty(value = "registries")
    private List<ObservedString> registries;

    /*
     * The sources property.
     */
    @JsonProperty(value = "sources")
    private List<Source> sources;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The registrarCreatedAt property.
     */
    @JsonProperty(value = "registrarCreatedAt")
    private List<ObservedLong> registrarCreatedAt;

    /*
     * The registrarUpdatedAt property.
     */
    @JsonProperty(value = "registrarUpdatedAt")
    private List<ObservedLong> registrarUpdatedAt;

    /*
     * The registrantContacts property.
     */
    @JsonProperty(value = "registrantContacts")
    private List<ObservedString> registrantContacts;

    /*
     * The adminContacts property.
     */
    @JsonProperty(value = "adminContacts")
    private List<ObservedString> adminContacts;

    /*
     * The technicalContacts property.
     */
    @JsonProperty(value = "technicalContacts")
    private List<ObservedString> technicalContacts;

    /*
     * The registrarNames property.
     */
    @JsonProperty(value = "registrarNames")
    private List<ObservedString> registrarNames;

    /*
     * The registrantNames property.
     */
    @JsonProperty(value = "registrantNames")
    private List<ObservedString> registrantNames;

    /*
     * The adminNames property.
     */
    @JsonProperty(value = "adminNames")
    private List<ObservedString> adminNames;

    /*
     * The technicalNames property.
     */
    @JsonProperty(value = "technicalNames")
    private List<ObservedString> technicalNames;

    /*
     * The adminOrgs property.
     */
    @JsonProperty(value = "adminOrgs")
    private List<ObservedString> adminOrgs;

    /*
     * The technicalOrgs property.
     */
    @JsonProperty(value = "technicalOrgs")
    private List<ObservedString> technicalOrgs;

    /*
     * The registrantPhones property.
     */
    @JsonProperty(value = "registrantPhones")
    private List<ObservedString> registrantPhones;

    /*
     * The adminPhones property.
     */
    @JsonProperty(value = "adminPhones")
    private List<ObservedString> adminPhones;

    /*
     * The technicalPhones property.
     */
    @JsonProperty(value = "technicalPhones")
    private List<ObservedString> technicalPhones;

    /*
     * The detailedFromWhoisAt property.
     */
    @JsonProperty(value = "detailedFromWhoisAt")
    private OffsetDateTime detailedFromWhoisAt;

    /** Creates an instance of AsAsset class. */
    private AsAsset() {}

    /**
     * Get the asn property: The asn property.
     *
     * @return the asn value.
     */
    public Long getAsn() {
        return this.asn;
    }

    /**
     * Get the asNames property: The asNames property.
     *
     * @return the asNames value.
     */
    public List<ObservedString> getAsNames() {
        return this.asNames;
    }

    /**
     * Get the orgNames property: The orgNames property.
     *
     * @return the orgNames value.
     */
    public List<ObservedString> getOrgNames() {
        return this.orgNames;
    }

    /**
     * Get the orgIds property: The orgIds property.
     *
     * @return the orgIds value.
     */
    public List<ObservedString> getOrgIds() {
        return this.orgIds;
    }

    /**
     * Get the countries property: The countries property.
     *
     * @return the countries value.
     */
    public List<ObservedString> getCountries() {
        return this.countries;
    }

    /**
     * Get the registries property: The registries property.
     *
     * @return the registries value.
     */
    public List<ObservedString> getRegistries() {
        return this.registries;
    }

    /**
     * Get the sources property: The sources property.
     *
     * @return the sources value.
     */
    public List<Source> getSources() {
        return this.sources;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the registrarCreatedAt property: The registrarCreatedAt property.
     *
     * @return the registrarCreatedAt value.
     */
    public List<ObservedLong> getRegistrarCreatedAt() {
        return this.registrarCreatedAt;
    }

    /**
     * Get the registrarUpdatedAt property: The registrarUpdatedAt property.
     *
     * @return the registrarUpdatedAt value.
     */
    public List<ObservedLong> getRegistrarUpdatedAt() {
        return this.registrarUpdatedAt;
    }

    /**
     * Get the registrantContacts property: The registrantContacts property.
     *
     * @return the registrantContacts value.
     */
    public List<ObservedString> getRegistrantContacts() {
        return this.registrantContacts;
    }

    /**
     * Get the adminContacts property: The adminContacts property.
     *
     * @return the adminContacts value.
     */
    public List<ObservedString> getAdminContacts() {
        return this.adminContacts;
    }

    /**
     * Get the technicalContacts property: The technicalContacts property.
     *
     * @return the technicalContacts value.
     */
    public List<ObservedString> getTechnicalContacts() {
        return this.technicalContacts;
    }

    /**
     * Get the registrarNames property: The registrarNames property.
     *
     * @return the registrarNames value.
     */
    public List<ObservedString> getRegistrarNames() {
        return this.registrarNames;
    }

    /**
     * Get the registrantNames property: The registrantNames property.
     *
     * @return the registrantNames value.
     */
    public List<ObservedString> getRegistrantNames() {
        return this.registrantNames;
    }

    /**
     * Get the adminNames property: The adminNames property.
     *
     * @return the adminNames value.
     */
    public List<ObservedString> getAdminNames() {
        return this.adminNames;
    }

    /**
     * Get the technicalNames property: The technicalNames property.
     *
     * @return the technicalNames value.
     */
    public List<ObservedString> getTechnicalNames() {
        return this.technicalNames;
    }

    /**
     * Get the adminOrgs property: The adminOrgs property.
     *
     * @return the adminOrgs value.
     */
    public List<ObservedString> getAdminOrgs() {
        return this.adminOrgs;
    }

    /**
     * Get the technicalOrgs property: The technicalOrgs property.
     *
     * @return the technicalOrgs value.
     */
    public List<ObservedString> getTechnicalOrgs() {
        return this.technicalOrgs;
    }

    /**
     * Get the registrantPhones property: The registrantPhones property.
     *
     * @return the registrantPhones value.
     */
    public List<ObservedString> getRegistrantPhones() {
        return this.registrantPhones;
    }

    /**
     * Get the adminPhones property: The adminPhones property.
     *
     * @return the adminPhones value.
     */
    public List<ObservedString> getAdminPhones() {
        return this.adminPhones;
    }

    /**
     * Get the technicalPhones property: The technicalPhones property.
     *
     * @return the technicalPhones value.
     */
    public List<ObservedString> getTechnicalPhones() {
        return this.technicalPhones;
    }

    /**
     * Get the detailedFromWhoisAt property: The detailedFromWhoisAt property.
     *
     * @return the detailedFromWhoisAt value.
     */
    public OffsetDateTime getDetailedFromWhoisAt() {
        return this.detailedFromWhoisAt;
    }
}
