// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** AssetSecurityPolicy. */
@Immutable
public final class AssetSecurityPolicy {
    /*
     * The policyName property.
     */
    @JsonProperty(value = "policyName")
    private String policyName;

    /*
     * The isAffected property.
     */
    @JsonProperty(value = "isAffected")
    private Boolean isAffected;

    /*
     * The description property.
     */
    @JsonProperty(value = "description")
    private String description;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The recent property.
     */
    @JsonProperty(value = "recent")
    private Boolean recent;

    /*
     * The sources property.
     */
    @JsonProperty(value = "sources")
    private List<Source> sources;

    /** Creates an instance of AssetSecurityPolicy class. */
    private AssetSecurityPolicy() {}

    /**
     * Get the policyName property: The policyName property.
     *
     * @return the policyName value.
     */
    public String getPolicyName() {
        return this.policyName;
    }

    /**
     * Get the isAffected property: The isAffected property.
     *
     * @return the isAffected value.
     */
    public Boolean isAffected() {
        return this.isAffected;
    }

    /**
     * Get the description property: The description property.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the recent property: The recent property.
     *
     * @return the recent value.
     */
    public Boolean isRecent() {
        return this.recent;
    }

    /**
     * Get the sources property: The sources property.
     *
     * @return the sources value.
     */
    public List<Source> getSources() {
        return this.sources;
    }
}
