// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for AssetUpdateState. */
public final class AssetUpdateState extends ExpandableStringEnum<AssetUpdateState> {
    /** Static value candidate for AssetUpdateState. */
    public static final AssetUpdateState CANDIDATE = fromString("candidate");

    /** Static value confirmed for AssetUpdateState. */
    public static final AssetUpdateState CONFIRMED = fromString("confirmed");

    /** Static value dismissed for AssetUpdateState. */
    public static final AssetUpdateState DISMISSED = fromString("dismissed");

    /** Static value candidateInvestigate for AssetUpdateState. */
    public static final AssetUpdateState CANDIDATE_INVESTIGATE = fromString("candidateInvestigate");

    /** Static value associatedPartner for AssetUpdateState. */
    public static final AssetUpdateState ASSOCIATED_PARTNER = fromString("associatedPartner");

    /** Static value associatedThirdparty for AssetUpdateState. */
    public static final AssetUpdateState ASSOCIATED_THIRDPARTY = fromString("associatedThirdparty");

    /**
     * Creates a new instance of AssetUpdateState value.
     *
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public AssetUpdateState() {}

    /**
     * Creates or finds a AssetUpdateState from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding AssetUpdateState.
     */
    @JsonCreator
    public static AssetUpdateState fromString(String name) {
        return fromString(name, AssetUpdateState.class);
    }

    /**
     * Gets known AssetUpdateState values.
     *
     * @return known AssetUpdateState values.
     */
    public static Collection<AssetUpdateState> values() {
        return values(AssetUpdateState.class);
    }
}
