// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** AssetSummaryResponse. */
@Immutable
public final class AssetSummaryResponse {
    /*
     * The name of the summary response.  Depending on the request time this will either be the asset filter, risk
     * category, or risk metric.
     */
    @JsonProperty(value = "displayName")
    private String displayName;

    /*
     * The description of the summary response.  Filters don't have a description.
     */
    @JsonProperty(value = "description")
    private String description;

    /*
     * The last time risk categories or risk metrics were captured. Set to the current time for asset filter requests,
     * which always pull the live asset data.
     */
    @JsonProperty(value = "updatedAt")
    private OffsetDateTime updatedAt;

    /*
     * If the request is for a metric category, this will contain the requested unique category name.
     */
    @JsonProperty(value = "metricCategory")
    private String metricCategory;

    /*
     * If the request is for a metric, this will contain the requested unique metric name.
     */
    @JsonProperty(value = "metric")
    private String metric;

    /*
     * If the request is for an asset filter, this will contain the corresponding filter.
     */
    @JsonProperty(value = "filter")
    private String filter;

    /*
     * An optional label used to filter requests results.
     */
    @JsonProperty(value = "labelName")
    private String labelName;

    /*
     * The count of assets matching the request parameters.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The link to the corresponding asset details.
     */
    @JsonProperty(value = "link")
    private String link;

    /*
     * The corresponding child entities.  For metric categories this will contain metrics.  For filters with groupBy
     * and segmentBy this will contain facets.
     */
    @JsonProperty(value = "children")
    private List<AssetSummaryResponse> children;

    /** Creates an instance of AssetSummaryResponse class. */
    private AssetSummaryResponse() {}

    /**
     * Get the displayName property: The name of the summary response. Depending on the request time this will either be
     * the asset filter, risk category, or risk metric.
     *
     * @return the displayName value.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Get the description property: The description of the summary response. Filters don't have a description.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Get the updatedAt property: The last time risk categories or risk metrics were captured. Set to the current time
     * for asset filter requests, which always pull the live asset data.
     *
     * @return the updatedAt value.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Get the metricCategory property: If the request is for a metric category, this will contain the requested unique
     * category name.
     *
     * @return the metricCategory value.
     */
    public String getMetricCategory() {
        return this.metricCategory;
    }

    /**
     * Get the metric property: If the request is for a metric, this will contain the requested unique metric name.
     *
     * @return the metric value.
     */
    public String getMetric() {
        return this.metric;
    }

    /**
     * Get the filter property: If the request is for an asset filter, this will contain the corresponding filter.
     *
     * @return the filter value.
     */
    public String getFilter() {
        return this.filter;
    }

    /**
     * Get the labelName property: An optional label used to filter requests results.
     *
     * @return the labelName value.
     */
    public String getLabelName() {
        return this.labelName;
    }

    /**
     * Get the count property: The count of assets matching the request parameters.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the link property: The link to the corresponding asset details.
     *
     * @return the link value.
     */
    public String getLink() {
        return this.link;
    }

    /**
     * Get the children property: The corresponding child entities. For metric categories this will contain metrics. For
     * filters with groupBy and segmentBy this will contain facets.
     *
     * @return the children value.
     */
    public List<AssetSummaryResponse> getChildren() {
        return this.children;
    }
}
