// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** AssetUpdateRequest. */
@Fluent
public final class AssetUpdateRequest {
    /*
     * The state to update the asset to.
     */
    @JsonProperty(value = "state")
    private AssetUpdateState state;

    /*
     * A string which can be used to identify the asset in external systems.
     */
    @JsonProperty(value = "externalId")
    private String externalId;

    /*
     * Any Labels to update the asset with.
     */
    @JsonProperty(value = "labels")
    private Object labels;

    /*
     * A list of asset types to cascade the updates to.
     */
    @JsonProperty(value = "transfers")
    private AssetUpdateTransfers transfers;

    /** Creates an instance of AssetUpdateRequest class. */
    public AssetUpdateRequest() {}

    /**
     * Get the state property: The state to update the asset to.
     *
     * @return the state value.
     */
    public AssetUpdateState getState() {
        return this.state;
    }

    /**
     * Set the state property: The state to update the asset to.
     *
     * @param state the state value to set.
     * @return the AssetUpdateRequest object itself.
     */
    public AssetUpdateRequest setState(AssetUpdateState state) {
        this.state = state;
        return this;
    }

    /**
     * Get the externalId property: A string which can be used to identify the asset in external systems.
     *
     * @return the externalId value.
     */
    public String getExternalId() {
        return this.externalId;
    }

    /**
     * Set the externalId property: A string which can be used to identify the asset in external systems.
     *
     * @param externalId the externalId value to set.
     * @return the AssetUpdateRequest object itself.
     */
    public AssetUpdateRequest setExternalId(String externalId) {
        this.externalId = externalId;
        return this;
    }

    /**
     * Get the labels property: Any Labels to update the asset with.
     *
     * @return the labels value.
     */
    public Object getLabels() {
        return this.labels;
    }

    /**
     * Set the labels property: Any Labels to update the asset with.
     *
     * @param labels the labels value to set.
     * @return the AssetUpdateRequest object itself.
     */
    public AssetUpdateRequest setLabels(Object labels) {
        this.labels = labels;
        return this;
    }

    /**
     * Get the transfers property: A list of asset types to cascade the updates to.
     *
     * @return the transfers value.
     */
    public AssetUpdateTransfers getTransfers() {
        return this.transfers;
    }

    /**
     * Set the transfers property: A list of asset types to cascade the updates to.
     *
     * @param transfers the transfers value to set.
     * @return the AssetUpdateRequest object itself.
     */
    public AssetUpdateRequest setTransfers(AssetUpdateTransfers transfers) {
        this.transfers = transfers;
        return this;
    }
}
