// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/** AuditTrailItem. */
@Immutable
public final class AuditTrailItem {
    /*
     * The system generated unique id for the resource.
     */
    @JsonProperty(value = "id")
    private String id;

    /*
     * The caller provided unique name for the resource.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * The name that can be used for display purposes.
     */
    @JsonProperty(value = "displayName")
    private String displayName;

    /*
     * The kind of asset.
     */
    @JsonProperty(value = "kind")
    private AuditTrailItemKind kind;

    /*
     * An explanation of why this audit trail node was discovered from the previous node.
     */
    @JsonProperty(value = "reason")
    private String reason;

    /** Creates an instance of AuditTrailItem class. */
    private AuditTrailItem() {}

    /**
     * Get the id property: The system generated unique id for the resource.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Get the name property: The caller provided unique name for the resource.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Get the displayName property: The name that can be used for display purposes.
     *
     * @return the displayName value.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Get the kind property: The kind of asset.
     *
     * @return the kind value.
     */
    public AuditTrailItemKind getKind() {
        return this.kind;
    }

    /**
     * Get the reason property: An explanation of why this audit trail node was discovered from the previous node.
     *
     * @return the reason value.
     */
    public String getReason() {
        return this.reason;
    }
}
