// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The AzureDataExplorerDataConnectionRequest model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("azureDataExplorer")
@Fluent
public final class AzureDataExplorerDataConnectionRequest extends DataConnectionRequest {
    /*
     * The properties property.
     */
    @JsonProperty(value = "properties", required = true)
    private AzureDataExplorerDataConnectionProperties properties;

    /**
     * Creates an instance of AzureDataExplorerDataConnectionRequest class.
     *
     * @param properties the properties value to set.
     * @param properties the properties value to set.
     */
    @JsonCreator
    public AzureDataExplorerDataConnectionRequest(
            @JsonProperty(value = "properties", required = true) Object properties,
            @JsonProperty(value = "properties", required = true) AzureDataExplorerDataConnectionProperties properties) {
        super(properties);
        this.properties = properties;
    }

    /**
     * Get the properties property: The properties property.
     *
     * @return the properties value.
     */
    public AzureDataExplorerDataConnectionProperties getProperties() {
        return this.properties;
    }

    /** {@inheritDoc} */
    @Override
    public AzureDataExplorerDataConnectionRequest setName(String name) {
        super.setName(name);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public AzureDataExplorerDataConnectionRequest setContent(DataConnectionContent content) {
        super.setContent(content);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public AzureDataExplorerDataConnectionRequest setFrequency(DataConnectionFrequency frequency) {
        super.setFrequency(frequency);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public AzureDataExplorerDataConnectionRequest setFrequencyOffset(Integer frequencyOffset) {
        super.setFrequencyOffset(frequencyOffset);
        return this;
    }
}
