// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** AzureDataExplorerDataConnectionProperties. */
@Fluent
public final class AzureDataExplorerDataConnectionProperties {
    /*
     * The azure data explorer cluster name
     */
    @JsonProperty(value = "clusterName")
    private String clusterName;

    /*
     * The azure data explorer region
     */
    @JsonProperty(value = "region")
    private String region;

    /*
     * The azure data explorer database name
     */
    @JsonProperty(value = "databaseName")
    private String databaseName;

    /** Creates an instance of AzureDataExplorerDataConnectionProperties class. */
    public AzureDataExplorerDataConnectionProperties() {}

    /**
     * Get the clusterName property: The azure data explorer cluster name.
     *
     * @return the clusterName value.
     */
    public String getClusterName() {
        return this.clusterName;
    }

    /**
     * Set the clusterName property: The azure data explorer cluster name.
     *
     * @param clusterName the clusterName value to set.
     * @return the AzureDataExplorerDataConnectionProperties object itself.
     */
    public AzureDataExplorerDataConnectionProperties setClusterName(String clusterName) {
        this.clusterName = clusterName;
        return this;
    }

    /**
     * Get the region property: The azure data explorer region.
     *
     * @return the region value.
     */
    public String getRegion() {
        return this.region;
    }

    /**
     * Set the region property: The azure data explorer region.
     *
     * @param region the region value to set.
     * @return the AzureDataExplorerDataConnectionProperties object itself.
     */
    public AzureDataExplorerDataConnectionProperties setRegion(String region) {
        this.region = region;
        return this;
    }

    /**
     * Get the databaseName property: The azure data explorer database name.
     *
     * @return the databaseName value.
     */
    public String getDatabaseName() {
        return this.databaseName;
    }

    /**
     * Set the databaseName property: The azure data explorer database name.
     *
     * @param databaseName the databaseName value to set.
     * @return the AzureDataExplorerDataConnectionProperties object itself.
     */
    public AzureDataExplorerDataConnectionProperties setDatabaseName(String databaseName) {
        this.databaseName = databaseName;
        return this;
    }
}
