// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** Banner. */
@Immutable
public final class Banner {
    /*
     * The port property.
     */
    @JsonProperty(value = "port")
    private Integer port;

    /*
     * The banner property.
     */
    @JsonProperty(value = "banner")
    private String banner;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The scanType property.
     */
    @JsonProperty(value = "scanType")
    private String scanType;

    /*
     * The bannerMetadata property.
     */
    @JsonProperty(value = "bannerMetadata")
    private String bannerMetadata;

    /*
     * The recent property.
     */
    @JsonProperty(value = "recent")
    private Boolean recent;

    /*
     * The sha256 property.
     */
    @JsonProperty(value = "sha256")
    private String sha256;

    /*
     * The sources property.
     */
    @JsonProperty(value = "sources")
    private List<Source> sources;

    /** Creates an instance of Banner class. */
    private Banner() {}

    /**
     * Get the port property: The port property.
     *
     * @return the port value.
     */
    public Integer getPort() {
        return this.port;
    }

    /**
     * Get the banner property: The banner property.
     *
     * @return the banner value.
     */
    public String getBanner() {
        return this.banner;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the scanType property: The scanType property.
     *
     * @return the scanType value.
     */
    public String getScanType() {
        return this.scanType;
    }

    /**
     * Get the bannerMetadata property: The bannerMetadata property.
     *
     * @return the bannerMetadata value.
     */
    public String getBannerMetadata() {
        return this.bannerMetadata;
    }

    /**
     * Get the recent property: The recent property.
     *
     * @return the recent value.
     */
    public Boolean isRecent() {
        return this.recent;
    }

    /**
     * Get the sha256 property: The sha256 property.
     *
     * @return the sha256 value.
     */
    public String getSha256() {
        return this.sha256;
    }

    /**
     * Get the sources property: The sources property.
     *
     * @return the sources value.
     */
    public List<Source> getSources() {
        return this.sources;
    }
}
