// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** ContactAsset. */
@Immutable
public final class ContactAsset {
    /*
     * The email property.
     */
    @JsonProperty(value = "email")
    private String email;

    /*
     * The names property.
     */
    @JsonProperty(value = "names")
    private List<ObservedString> names;

    /*
     * The organizations property.
     */
    @JsonProperty(value = "organizations")
    private List<ObservedString> organizations;

    /*
     * The sources property.
     */
    @JsonProperty(value = "sources")
    private List<Source> sources;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /** Creates an instance of ContactAsset class. */
    private ContactAsset() {}

    /**
     * Get the email property: The email property.
     *
     * @return the email value.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Get the names property: The names property.
     *
     * @return the names value.
     */
    public List<ObservedString> getNames() {
        return this.names;
    }

    /**
     * Get the organizations property: The organizations property.
     *
     * @return the organizations value.
     */
    public List<ObservedString> getOrganizations() {
        return this.organizations;
    }

    /**
     * Get the sources property: The sources property.
     *
     * @return the sources value.
     */
    public List<Source> getSources() {
        return this.sources;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }
}
