// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** Cookie. */
@Immutable
public final class Cookie {
    /*
     * The cookieName property.
     */
    @JsonProperty(value = "cookieName")
    private String cookieName;

    /*
     * The cookieDomain property.
     */
    @JsonProperty(value = "cookieDomain")
    private String cookieDomain;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The recent property.
     */
    @JsonProperty(value = "recent")
    private Boolean recent;

    /*
     * The cookieExpiryDate property.
     */
    @JsonProperty(value = "cookieExpiryDate")
    private OffsetDateTime cookieExpiryDate;

    /** Creates an instance of Cookie class. */
    private Cookie() {}

    /**
     * Get the cookieName property: The cookieName property.
     *
     * @return the cookieName value.
     */
    public String getCookieName() {
        return this.cookieName;
    }

    /**
     * Get the cookieDomain property: The cookieDomain property.
     *
     * @return the cookieDomain value.
     */
    public String getCookieDomain() {
        return this.cookieDomain;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the recent property: The recent property.
     *
     * @return the recent value.
     */
    public Boolean isRecent() {
        return this.recent;
    }

    /**
     * Get the cookieExpiryDate property: The cookieExpiryDate property.
     *
     * @return the cookieExpiryDate value.
     */
    public OffsetDateTime getCookieExpiryDate() {
        return this.cookieExpiryDate;
    }
}
