// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Cve. */
@Immutable
public final class Cve {
    /*
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * The cweId property.
     */
    @JsonProperty(value = "cweId")
    private String cweId;

    /*
     * The cvssScore property.
     */
    @JsonProperty(value = "cvssScore")
    private Double cvssScore;

    /*
     * The cvss3Summary property.
     */
    @JsonProperty(value = "cvss3Summary", required = true)
    private CVSS3Summary cvss3Summary;

    /**
     * Creates an instance of Cve class.
     *
     * @param cvss3Summary the cvss3Summary value to set.
     */
    @JsonCreator
    private Cve(@JsonProperty(value = "cvss3Summary", required = true) CVSS3Summary cvss3Summary) {
        this.cvss3Summary = cvss3Summary;
    }

    /**
     * Get the name property: The name property.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Get the cweId property: The cweId property.
     *
     * @return the cweId value.
     */
    public String getCweId() {
        return this.cweId;
    }

    /**
     * Get the cvssScore property: The cvssScore property.
     *
     * @return the cvssScore value.
     */
    public Double getCvssScore() {
        return this.cvssScore;
    }

    /**
     * Get the cvss3Summary property: The cvss3Summary property.
     *
     * @return the cvss3Summary value.
     */
    public CVSS3Summary getCvss3Summary() {
        return this.cvss3Summary;
    }
}
