// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/** CVSS3Summary. */
@Immutable
public final class CVSS3Summary {
    /*
     * The version property.
     */
    @JsonProperty(value = "version")
    private String version;

    /*
     * The vectorString property.
     */
    @JsonProperty(value = "vectorString")
    private String vectorString;

    /*
     * The attackVector property.
     */
    @JsonProperty(value = "attackVector")
    private String attackVector;

    /*
     * The attackComplexity property.
     */
    @JsonProperty(value = "attackComplexity")
    private String attackComplexity;

    /*
     * The privilegesRequired property.
     */
    @JsonProperty(value = "privilegesRequired")
    private String privilegesRequired;

    /*
     * The userInteraction property.
     */
    @JsonProperty(value = "userInteraction")
    private String userInteraction;

    /*
     * The scope property.
     */
    @JsonProperty(value = "scope")
    private String scope;

    /*
     * The confidentialityImpact property.
     */
    @JsonProperty(value = "confidentialityImpact")
    private String confidentialityImpact;

    /*
     * The integrityImpact property.
     */
    @JsonProperty(value = "integrityImpact")
    private String integrityImpact;

    /*
     * The availabilityImpact property.
     */
    @JsonProperty(value = "availabilityImpact")
    private String availabilityImpact;

    /*
     * The baseScore property.
     */
    @JsonProperty(value = "baseScore")
    private Double baseScore;

    /*
     * The baseSeverity property.
     */
    @JsonProperty(value = "baseSeverity")
    private String baseSeverity;

    /*
     * The exploitCodeMaturity property.
     */
    @JsonProperty(value = "exploitCodeMaturity")
    private String exploitCodeMaturity;

    /*
     * The remediationLevel property.
     */
    @JsonProperty(value = "remediationLevel")
    private String remediationLevel;

    /*
     * The reportConfidence property.
     */
    @JsonProperty(value = "reportConfidence")
    private String reportConfidence;

    /*
     * The exploitabilityScore property.
     */
    @JsonProperty(value = "exploitabilityScore")
    private Double exploitabilityScore;

    /*
     * The impactScore property.
     */
    @JsonProperty(value = "impactScore")
    private Double impactScore;

    /** Creates an instance of CVSS3Summary class. */
    private CVSS3Summary() {}

    /**
     * Get the version property: The version property.
     *
     * @return the version value.
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * Get the vectorString property: The vectorString property.
     *
     * @return the vectorString value.
     */
    public String getVectorString() {
        return this.vectorString;
    }

    /**
     * Get the attackVector property: The attackVector property.
     *
     * @return the attackVector value.
     */
    public String getAttackVector() {
        return this.attackVector;
    }

    /**
     * Get the attackComplexity property: The attackComplexity property.
     *
     * @return the attackComplexity value.
     */
    public String getAttackComplexity() {
        return this.attackComplexity;
    }

    /**
     * Get the privilegesRequired property: The privilegesRequired property.
     *
     * @return the privilegesRequired value.
     */
    public String getPrivilegesRequired() {
        return this.privilegesRequired;
    }

    /**
     * Get the userInteraction property: The userInteraction property.
     *
     * @return the userInteraction value.
     */
    public String getUserInteraction() {
        return this.userInteraction;
    }

    /**
     * Get the scope property: The scope property.
     *
     * @return the scope value.
     */
    public String getScope() {
        return this.scope;
    }

    /**
     * Get the confidentialityImpact property: The confidentialityImpact property.
     *
     * @return the confidentialityImpact value.
     */
    public String getConfidentialityImpact() {
        return this.confidentialityImpact;
    }

    /**
     * Get the integrityImpact property: The integrityImpact property.
     *
     * @return the integrityImpact value.
     */
    public String getIntegrityImpact() {
        return this.integrityImpact;
    }

    /**
     * Get the availabilityImpact property: The availabilityImpact property.
     *
     * @return the availabilityImpact value.
     */
    public String getAvailabilityImpact() {
        return this.availabilityImpact;
    }

    /**
     * Get the baseScore property: The baseScore property.
     *
     * @return the baseScore value.
     */
    public Double getBaseScore() {
        return this.baseScore;
    }

    /**
     * Get the baseSeverity property: The baseSeverity property.
     *
     * @return the baseSeverity value.
     */
    public String getBaseSeverity() {
        return this.baseSeverity;
    }

    /**
     * Get the exploitCodeMaturity property: The exploitCodeMaturity property.
     *
     * @return the exploitCodeMaturity value.
     */
    public String getExploitCodeMaturity() {
        return this.exploitCodeMaturity;
    }

    /**
     * Get the remediationLevel property: The remediationLevel property.
     *
     * @return the remediationLevel value.
     */
    public String getRemediationLevel() {
        return this.remediationLevel;
    }

    /**
     * Get the reportConfidence property: The reportConfidence property.
     *
     * @return the reportConfidence value.
     */
    public String getReportConfidence() {
        return this.reportConfidence;
    }

    /**
     * Get the exploitabilityScore property: The exploitabilityScore property.
     *
     * @return the exploitabilityScore value.
     */
    public Double getExploitabilityScore() {
        return this.exploitabilityScore;
    }

    /**
     * Get the impactScore property: The impactScore property.
     *
     * @return the impactScore value.
     */
    public Double getImpactScore() {
        return this.impactScore;
    }
}
