// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for DataConnectionContent. */
public final class DataConnectionContent extends ExpandableStringEnum<DataConnectionContent> {
    /** Static value assets for DataConnectionContent. */
    public static final DataConnectionContent ASSETS = fromString("assets");

    /** Static value attackSurfaceInsights for DataConnectionContent. */
    public static final DataConnectionContent ATTACK_SURFACE_INSIGHTS = fromString("attackSurfaceInsights");

    /**
     * Creates a new instance of DataConnectionContent value.
     *
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public DataConnectionContent() {}

    /**
     * Creates or finds a DataConnectionContent from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding DataConnectionContent.
     */
    @JsonCreator
    public static DataConnectionContent fromString(String name) {
        return fromString(name, DataConnectionContent.class);
    }

    /**
     * Gets known DataConnectionContent values.
     *
     * @return known DataConnectionContent values.
     */
    public static Collection<DataConnectionContent> values() {
        return values(DataConnectionContent.class);
    }
}
