// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** DataConnectionRequest. */
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "kind",
        defaultImpl = DataConnectionRequest.class)
@JsonTypeName("DataConnectionRequest")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "logAnalytics", value = LogAnalyticsDataConnectionRequest.class),
    @JsonSubTypes.Type(name = "azureDataExplorer", value = AzureDataExplorerDataConnectionRequest.class)
})
@Fluent
public class DataConnectionRequest {
    /*
     * The name of data connection
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * The type of data the data connection will transfer.
     */
    @JsonProperty(value = "content")
    private DataConnectionContent content;

    /*
     * The properties property.
     */
    @JsonProperty(value = "properties", required = true)
    private Object properties;

    /*
     * The rate at which the data connection will receive updates.
     */
    @JsonProperty(value = "frequency")
    private DataConnectionFrequency frequency;

    /*
     * The day to update the data connection on. (1-7 for weekly, 1-31 for monthly)
     */
    @JsonProperty(value = "frequencyOffset")
    private Integer frequencyOffset;

    /**
     * Creates an instance of DataConnectionRequest class.
     *
     * @param properties the properties value to set.
     */
    @JsonCreator
    public DataConnectionRequest(@JsonProperty(value = "properties", required = true) Object properties) {
        this.properties = properties;
    }

    /**
     * Get the name property: The name of data connection.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name property: The name of data connection.
     *
     * @param name the name value to set.
     * @return the DataConnectionRequest object itself.
     */
    public DataConnectionRequest setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the content property: The type of data the data connection will transfer.
     *
     * @return the content value.
     */
    public DataConnectionContent getContent() {
        return this.content;
    }

    /**
     * Set the content property: The type of data the data connection will transfer.
     *
     * @param content the content value to set.
     * @return the DataConnectionRequest object itself.
     */
    public DataConnectionRequest setContent(DataConnectionContent content) {
        this.content = content;
        return this;
    }

    /**
     * Get the properties property: The properties property.
     *
     * @return the properties value.
     */
    public Object getProperties() {
        return this.properties;
    }

    /**
     * Get the frequency property: The rate at which the data connection will receive updates.
     *
     * @return the frequency value.
     */
    public DataConnectionFrequency getFrequency() {
        return this.frequency;
    }

    /**
     * Set the frequency property: The rate at which the data connection will receive updates.
     *
     * @param frequency the frequency value to set.
     * @return the DataConnectionRequest object itself.
     */
    public DataConnectionRequest setFrequency(DataConnectionFrequency frequency) {
        this.frequency = frequency;
        return this;
    }

    /**
     * Get the frequencyOffset property: The day to update the data connection on. (1-7 for weekly, 1-31 for monthly).
     *
     * @return the frequencyOffset value.
     */
    public Integer getFrequencyOffset() {
        return this.frequencyOffset;
    }

    /**
     * Set the frequencyOffset property: The day to update the data connection on. (1-7 for weekly, 1-31 for monthly).
     *
     * @param frequencyOffset the frequencyOffset value to set.
     * @return the DataConnectionRequest object itself.
     */
    public DataConnectionRequest setFrequencyOffset(Integer frequencyOffset) {
        this.frequencyOffset = frequencyOffset;
        return this;
    }
}
