// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for DataConnectionFrequency. */
public final class DataConnectionFrequency extends ExpandableStringEnum<DataConnectionFrequency> {
    /** Static value daily for DataConnectionFrequency. */
    public static final DataConnectionFrequency DAILY = fromString("daily");

    /** Static value weekly for DataConnectionFrequency. */
    public static final DataConnectionFrequency WEEKLY = fromString("weekly");

    /** Static value monthly for DataConnectionFrequency. */
    public static final DataConnectionFrequency MONTHLY = fromString("monthly");

    /**
     * Creates a new instance of DataConnectionFrequency value.
     *
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public DataConnectionFrequency() {}

    /**
     * Creates or finds a DataConnectionFrequency from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding DataConnectionFrequency.
     */
    @JsonCreator
    public static DataConnectionFrequency fromString(String name) {
        return fromString(name, DataConnectionFrequency.class);
    }

    /**
     * Gets known DataConnectionFrequency values.
     *
     * @return known DataConnectionFrequency values.
     */
    public static Collection<DataConnectionFrequency> values() {
        return values(DataConnectionFrequency.class);
    }
}
