// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** DependentResource. */
@Immutable
public final class DependentResource {
    /*
     * The md5 property.
     */
    @JsonProperty(value = "md5")
    private String md5;

    /*
     * The responseBodySize property.
     */
    @JsonProperty(value = "responseBodySize")
    private Long responseBodySize;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The firstSeenCrawlGuid property.
     */
    @JsonProperty(value = "firstSeenCrawlGuid")
    private String firstSeenCrawlGuid;

    /*
     * The firstSeenPageGuid property.
     */
    @JsonProperty(value = "firstSeenPageGuid")
    private String firstSeenPageGuid;

    /*
     * The firstSeenResourceGuid property.
     */
    @JsonProperty(value = "firstSeenResourceGuid")
    private String firstSeenResourceGuid;

    /*
     * The lastSeenCrawlGuid property.
     */
    @JsonProperty(value = "lastSeenCrawlGuid")
    private String lastSeenCrawlGuid;

    /*
     * The lastSeenPageGuid property.
     */
    @JsonProperty(value = "lastSeenPageGuid")
    private String lastSeenPageGuid;

    /*
     * The lastSeenResourceGuid property.
     */
    @JsonProperty(value = "lastSeenResourceGuid")
    private String lastSeenResourceGuid;

    /*
     * The responseBodyMinhash property.
     */
    @JsonProperty(value = "responseBodyMinhash")
    private List<Integer> responseBodyMinhash;

    /*
     * The contentType property.
     */
    @JsonProperty(value = "contentType")
    private String contentType;

    /*
     * The sha256 property.
     */
    @JsonProperty(value = "sha256")
    private String sha256;

    /*
     * The sha384 property.
     */
    @JsonProperty(value = "sha384")
    private String sha384;

    /*
     * The sha512 property.
     */
    @JsonProperty(value = "sha512")
    private String sha512;

    /*
     * The url property.
     */
    @JsonProperty(value = "url")
    private String url;

    /*
     * The cached property.
     */
    @JsonProperty(value = "cached")
    private Boolean cached;

    /*
     * The sriChecks property.
     */
    @JsonProperty(value = "sriChecks")
    private List<SubResourceIntegrityCheck> sriChecks;

    /*
     * The host property.
     */
    @JsonProperty(value = "host")
    private String host;

    /*
     * The lastObservedViolation property.
     */
    @JsonProperty(value = "lastObservedViolation")
    private OffsetDateTime lastObservedViolation;

    /*
     * The lastObservedValidation property.
     */
    @JsonProperty(value = "lastObservedValidation")
    private OffsetDateTime lastObservedValidation;

    /*
     * The lastObservedActualSriHash property.
     */
    @JsonProperty(value = "lastObservedActualSriHash")
    private String lastObservedActualSriHash;

    /*
     * The lastObservedExpectedSriHash property.
     */
    @JsonProperty(value = "lastObservedExpectedSriHash")
    private String lastObservedExpectedSriHash;

    /** Creates an instance of DependentResource class. */
    private DependentResource() {}

    /**
     * Get the md5 property: The md5 property.
     *
     * @return the md5 value.
     */
    public String getMd5() {
        return this.md5;
    }

    /**
     * Get the responseBodySize property: The responseBodySize property.
     *
     * @return the responseBodySize value.
     */
    public Long getResponseBodySize() {
        return this.responseBodySize;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the firstSeenCrawlGuid property: The firstSeenCrawlGuid property.
     *
     * @return the firstSeenCrawlGuid value.
     */
    public String getFirstSeenCrawlGuid() {
        return this.firstSeenCrawlGuid;
    }

    /**
     * Get the firstSeenPageGuid property: The firstSeenPageGuid property.
     *
     * @return the firstSeenPageGuid value.
     */
    public String getFirstSeenPageGuid() {
        return this.firstSeenPageGuid;
    }

    /**
     * Get the firstSeenResourceGuid property: The firstSeenResourceGuid property.
     *
     * @return the firstSeenResourceGuid value.
     */
    public String getFirstSeenResourceGuid() {
        return this.firstSeenResourceGuid;
    }

    /**
     * Get the lastSeenCrawlGuid property: The lastSeenCrawlGuid property.
     *
     * @return the lastSeenCrawlGuid value.
     */
    public String getLastSeenCrawlGuid() {
        return this.lastSeenCrawlGuid;
    }

    /**
     * Get the lastSeenPageGuid property: The lastSeenPageGuid property.
     *
     * @return the lastSeenPageGuid value.
     */
    public String getLastSeenPageGuid() {
        return this.lastSeenPageGuid;
    }

    /**
     * Get the lastSeenResourceGuid property: The lastSeenResourceGuid property.
     *
     * @return the lastSeenResourceGuid value.
     */
    public String getLastSeenResourceGuid() {
        return this.lastSeenResourceGuid;
    }

    /**
     * Get the responseBodyMinhash property: The responseBodyMinhash property.
     *
     * @return the responseBodyMinhash value.
     */
    public List<Integer> getResponseBodyMinhash() {
        return this.responseBodyMinhash;
    }

    /**
     * Get the contentType property: The contentType property.
     *
     * @return the contentType value.
     */
    public String getContentType() {
        return this.contentType;
    }

    /**
     * Get the sha256 property: The sha256 property.
     *
     * @return the sha256 value.
     */
    public String getSha256() {
        return this.sha256;
    }

    /**
     * Get the sha384 property: The sha384 property.
     *
     * @return the sha384 value.
     */
    public String getSha384() {
        return this.sha384;
    }

    /**
     * Get the sha512 property: The sha512 property.
     *
     * @return the sha512 value.
     */
    public String getSha512() {
        return this.sha512;
    }

    /**
     * Get the url property: The url property.
     *
     * @return the url value.
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Get the cached property: The cached property.
     *
     * @return the cached value.
     */
    public Boolean isCached() {
        return this.cached;
    }

    /**
     * Get the sriChecks property: The sriChecks property.
     *
     * @return the sriChecks value.
     */
    public List<SubResourceIntegrityCheck> getSriChecks() {
        return this.sriChecks;
    }

    /**
     * Get the host property: The host property.
     *
     * @return the host value.
     */
    public String getHost() {
        return this.host;
    }

    /**
     * Get the lastObservedViolation property: The lastObservedViolation property.
     *
     * @return the lastObservedViolation value.
     */
    public OffsetDateTime getLastObservedViolation() {
        return this.lastObservedViolation;
    }

    /**
     * Get the lastObservedValidation property: The lastObservedValidation property.
     *
     * @return the lastObservedValidation value.
     */
    public OffsetDateTime getLastObservedValidation() {
        return this.lastObservedValidation;
    }

    /**
     * Get the lastObservedActualSriHash property: The lastObservedActualSriHash property.
     *
     * @return the lastObservedActualSriHash value.
     */
    public String getLastObservedActualSriHash() {
        return this.lastObservedActualSriHash;
    }

    /**
     * Get the lastObservedExpectedSriHash property: The lastObservedExpectedSriHash property.
     *
     * @return the lastObservedExpectedSriHash value.
     */
    public String getLastObservedExpectedSriHash() {
        return this.lastObservedExpectedSriHash;
    }
}
