// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** DiscoGroupRequest. */
@Fluent
public final class DiscoGroupRequest {
    /*
     * The name for a disco group.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * The description for a disco group.
     */
    @JsonProperty(value = "description")
    private String description;

    /*
     * The tier for the disco group which will affect the algorithm used for the disco runs in this group.
     */
    @JsonProperty(value = "tier")
    private String tier;

    /*
     * The frequency at which the disco group is supposed to be rerun in milliseconds.
     */
    @JsonProperty(value = "frequencyMilliseconds")
    private Long frequencyMilliseconds;

    /*
     * The list of seeds used for the disco group runs.
     */
    @JsonProperty(value = "seeds")
    private List<DiscoSource> seeds;

    /*
     * The list of names used for the disco group runs.
     */
    @JsonProperty(value = "names")
    private List<String> names;

    /*
     * The list of excludes used for the disco group runs, aka assets to exclude from the discovery algorithm.
     */
    @JsonProperty(value = "excludes")
    private List<DiscoSource> excludes;

    /*
     * The unique identifier for the disco template used for the disco group creation.
     */
    @JsonProperty(value = "templateId")
    private String templateId;

    /** Creates an instance of DiscoGroupRequest class. */
    public DiscoGroupRequest() {}

    /**
     * Get the name property: The name for a disco group.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name property: The name for a disco group.
     *
     * @param name the name value to set.
     * @return the DiscoGroupRequest object itself.
     */
    public DiscoGroupRequest setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the description property: The description for a disco group.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Set the description property: The description for a disco group.
     *
     * @param description the description value to set.
     * @return the DiscoGroupRequest object itself.
     */
    public DiscoGroupRequest setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the tier property: The tier for the disco group which will affect the algorithm used for the disco runs in
     * this group.
     *
     * @return the tier value.
     */
    public String getTier() {
        return this.tier;
    }

    /**
     * Set the tier property: The tier for the disco group which will affect the algorithm used for the disco runs in
     * this group.
     *
     * @param tier the tier value to set.
     * @return the DiscoGroupRequest object itself.
     */
    public DiscoGroupRequest setTier(String tier) {
        this.tier = tier;
        return this;
    }

    /**
     * Get the frequencyMilliseconds property: The frequency at which the disco group is supposed to be rerun in
     * milliseconds.
     *
     * @return the frequencyMilliseconds value.
     */
    public Long getFrequencyMilliseconds() {
        return this.frequencyMilliseconds;
    }

    /**
     * Set the frequencyMilliseconds property: The frequency at which the disco group is supposed to be rerun in
     * milliseconds.
     *
     * @param frequencyMilliseconds the frequencyMilliseconds value to set.
     * @return the DiscoGroupRequest object itself.
     */
    public DiscoGroupRequest setFrequencyMilliseconds(Long frequencyMilliseconds) {
        this.frequencyMilliseconds = frequencyMilliseconds;
        return this;
    }

    /**
     * Get the seeds property: The list of seeds used for the disco group runs.
     *
     * @return the seeds value.
     */
    public List<DiscoSource> getSeeds() {
        return this.seeds;
    }

    /**
     * Set the seeds property: The list of seeds used for the disco group runs.
     *
     * @param seeds the seeds value to set.
     * @return the DiscoGroupRequest object itself.
     */
    public DiscoGroupRequest setSeeds(List<DiscoSource> seeds) {
        this.seeds = seeds;
        return this;
    }

    /**
     * Get the names property: The list of names used for the disco group runs.
     *
     * @return the names value.
     */
    public List<String> getNames() {
        return this.names;
    }

    /**
     * Set the names property: The list of names used for the disco group runs.
     *
     * @param names the names value to set.
     * @return the DiscoGroupRequest object itself.
     */
    public DiscoGroupRequest setNames(List<String> names) {
        this.names = names;
        return this;
    }

    /**
     * Get the excludes property: The list of excludes used for the disco group runs, aka assets to exclude from the
     * discovery algorithm.
     *
     * @return the excludes value.
     */
    public List<DiscoSource> getExcludes() {
        return this.excludes;
    }

    /**
     * Set the excludes property: The list of excludes used for the disco group runs, aka assets to exclude from the
     * discovery algorithm.
     *
     * @param excludes the excludes value to set.
     * @return the DiscoGroupRequest object itself.
     */
    public DiscoGroupRequest setExcludes(List<DiscoSource> excludes) {
        this.excludes = excludes;
        return this;
    }

    /**
     * Get the templateId property: The unique identifier for the disco template used for the disco group creation.
     *
     * @return the templateId value.
     */
    public String getTemplateId() {
        return this.templateId;
    }

    /**
     * Set the templateId property: The unique identifier for the disco template used for the disco group creation.
     *
     * @param templateId the templateId value to set.
     * @return the DiscoGroupRequest object itself.
     */
    public DiscoGroupRequest setTemplateId(String templateId) {
        this.templateId = templateId;
        return this;
    }
}
