// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** DiscoSource. */
@Fluent
public final class DiscoSource {
    /*
     * The kind of disco source.
     */
    @JsonProperty(value = "kind")
    private DiscoSourceKind kind;

    /*
     * The name for the disco source.
     */
    @JsonProperty(value = "name")
    private String name;

    /** Creates an instance of DiscoSource class. */
    public DiscoSource() {}

    /**
     * Get the kind property: The kind of disco source.
     *
     * @return the kind value.
     */
    public DiscoSourceKind getKind() {
        return this.kind;
    }

    /**
     * Set the kind property: The kind of disco source.
     *
     * @param kind the kind value to set.
     * @return the DiscoSource object itself.
     */
    public DiscoSource setKind(DiscoSourceKind kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the name property: The name for the disco source.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name property: The name for the disco source.
     *
     * @param name the name value to set.
     * @return the DiscoSource object itself.
     */
    public DiscoSource setName(String name) {
        this.name = name;
        return this;
    }
}
