// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** DiscoRunPageResponse. */
@Immutable
public final class DiscoRunPageResponse {
    /*
     * The total number of items available in the full result set.
     */
    @JsonProperty(value = "totalElements")
    private Long totalElements;

    /*
     * The link to access the next page of results.  Not set if at the end of the result set.
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /*
     * The items in the current page of results.
     */
    @JsonProperty(value = "value", required = true)
    private List<DiscoRunResponse> value;

    /**
     * Creates an instance of DiscoRunPageResponse class.
     *
     * @param value the value value to set.
     */
    @JsonCreator
    private DiscoRunPageResponse(@JsonProperty(value = "value", required = true) List<DiscoRunResponse> value) {
        this.value = value;
    }

    /**
     * Get the totalElements property: The total number of items available in the full result set.
     *
     * @return the totalElements value.
     */
    public Long getTotalElements() {
        return this.totalElements;
    }

    /**
     * Get the nextLink property: The link to access the next page of results. Not set if at the end of the result set.
     *
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * Get the value property: The items in the current page of results.
     *
     * @return the value value.
     */
    public List<DiscoRunResponse> getValue() {
        return this.value;
    }
}
