// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** DiscoTemplateResponse. */
@Immutable
public final class DiscoTemplateResponse {
    /*
     * The system generated unique id for the resource.
     */
    @JsonProperty(value = "id")
    private String id;

    /*
     * The caller provided unique name for the resource.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * The name that can be used for display purposes.
     */
    @JsonProperty(value = "displayName")
    private String displayName;

    /*
     * The name of the industry.
     */
    @JsonProperty(value = "industry")
    private String industry;

    /*
     * The name of the region.
     */
    @JsonProperty(value = "region")
    private String region;

    /*
     * The country code.
     */
    @JsonProperty(value = "countryCode")
    private String countryCode;

    /*
     * The state code.
     */
    @JsonProperty(value = "stateCode")
    private String stateCode;

    /*
     * The name of the city.
     */
    @JsonProperty(value = "city")
    private String city;

    /*
     * The list of disco template seeds.
     */
    @JsonProperty(value = "seeds")
    private List<DiscoSource> seeds;

    /*
     * The list of disco template names.
     */
    @JsonProperty(value = "names")
    private List<String> names;

    /** Creates an instance of DiscoTemplateResponse class. */
    private DiscoTemplateResponse() {}

    /**
     * Get the id property: The system generated unique id for the resource.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Get the name property: The caller provided unique name for the resource.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Get the displayName property: The name that can be used for display purposes.
     *
     * @return the displayName value.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Get the industry property: The name of the industry.
     *
     * @return the industry value.
     */
    public String getIndustry() {
        return this.industry;
    }

    /**
     * Get the region property: The name of the region.
     *
     * @return the region value.
     */
    public String getRegion() {
        return this.region;
    }

    /**
     * Get the countryCode property: The country code.
     *
     * @return the countryCode value.
     */
    public String getCountryCode() {
        return this.countryCode;
    }

    /**
     * Get the stateCode property: The state code.
     *
     * @return the stateCode value.
     */
    public String getStateCode() {
        return this.stateCode;
    }

    /**
     * Get the city property: The name of the city.
     *
     * @return the city value.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Get the seeds property: The list of disco template seeds.
     *
     * @return the seeds value.
     */
    public List<DiscoSource> getSeeds() {
        return this.seeds;
    }

    /**
     * Get the names property: The list of disco template names.
     *
     * @return the names value.
     */
    public List<String> getNames() {
        return this.names;
    }
}
