// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** DiscoGroupResponse. */
@Immutable
public final class DiscoGroupResponse {
    /*
     * The system generated unique id for the resource.
     */
    @JsonProperty(value = "id")
    private String id;

    /*
     * The caller provided unique name for the resource.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * The name that can be used for display purposes.
     */
    @JsonProperty(value = "displayName")
    private String displayName;

    /*
     * The description for a disco group.
     */
    @JsonProperty(value = "description")
    private String description;

    /*
     * The tier for the disco group which will affect the algorithm used for the disco runs in this group.
     */
    @JsonProperty(value = "tier")
    private String tier;

    /*
     * The frequency at which the disco group is supposed to be rerun in milliseconds.
     */
    @JsonProperty(value = "frequencyMilliseconds")
    private Long frequencyMilliseconds;

    /*
     * The list of seeds used for the disco group runs.
     */
    @JsonProperty(value = "seeds")
    private List<DiscoSource> seeds;

    /*
     * The list of names used for the disco group runs.
     */
    @JsonProperty(value = "names")
    private List<String> names;

    /*
     * The list of excludes used for the disco group runs, aka assets to exclude from the discovery algorithm.
     */
    @JsonProperty(value = "excludes")
    private List<DiscoSource> excludes;

    /*
     * The latestRun property.
     */
    @JsonProperty(value = "latestRun", required = true)
    private DiscoRunResponse latestRun;

    /*
     * The date for the disco group was created.
     */
    @JsonProperty(value = "createdDate")
    private OffsetDateTime createdDate;

    /*
     * The unique identifier for the disco template used for the disco group creation.
     */
    @JsonProperty(value = "templateId")
    private String templateId;

    /**
     * Creates an instance of DiscoGroupResponse class.
     *
     * @param latestRun the latestRun value to set.
     */
    @JsonCreator
    private DiscoGroupResponse(@JsonProperty(value = "latestRun", required = true) DiscoRunResponse latestRun) {
        this.latestRun = latestRun;
    }

    /**
     * Get the id property: The system generated unique id for the resource.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Get the name property: The caller provided unique name for the resource.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Get the displayName property: The name that can be used for display purposes.
     *
     * @return the displayName value.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Get the description property: The description for a disco group.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Get the tier property: The tier for the disco group which will affect the algorithm used for the disco runs in
     * this group.
     *
     * @return the tier value.
     */
    public String getTier() {
        return this.tier;
    }

    /**
     * Get the frequencyMilliseconds property: The frequency at which the disco group is supposed to be rerun in
     * milliseconds.
     *
     * @return the frequencyMilliseconds value.
     */
    public Long getFrequencyMilliseconds() {
        return this.frequencyMilliseconds;
    }

    /**
     * Get the seeds property: The list of seeds used for the disco group runs.
     *
     * @return the seeds value.
     */
    public List<DiscoSource> getSeeds() {
        return this.seeds;
    }

    /**
     * Get the names property: The list of names used for the disco group runs.
     *
     * @return the names value.
     */
    public List<String> getNames() {
        return this.names;
    }

    /**
     * Get the excludes property: The list of excludes used for the disco group runs, aka assets to exclude from the
     * discovery algorithm.
     *
     * @return the excludes value.
     */
    public List<DiscoSource> getExcludes() {
        return this.excludes;
    }

    /**
     * Get the latestRun property: The latestRun property.
     *
     * @return the latestRun value.
     */
    public DiscoRunResponse getLatestRun() {
        return this.latestRun;
    }

    /**
     * Get the createdDate property: The date for the disco group was created.
     *
     * @return the createdDate value.
     */
    public OffsetDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Get the templateId property: The unique identifier for the disco template used for the disco group creation.
     *
     * @return the templateId value.
     */
    public String getTemplateId() {
        return this.templateId;
    }
}
