// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** DomainAsset. */
@Immutable
public final class DomainAsset {
    /*
     * The domain property.
     */
    @JsonProperty(value = "domain")
    private String domain;

    /*
     * The whoisId property.
     */
    @JsonProperty(value = "whoisId")
    private Long whoisId;

    /*
     * The registrarIanaIds property.
     */
    @JsonProperty(value = "registrarIanaIds")
    private List<ObservedInteger> registrarIanaIds;

    /*
     * The registrantContacts property.
     */
    @JsonProperty(value = "registrantContacts")
    private List<ObservedString> registrantContacts;

    /*
     * The registrantOrgs property.
     */
    @JsonProperty(value = "registrantOrgs")
    private List<ObservedString> registrantOrgs;

    /*
     * The adminContacts property.
     */
    @JsonProperty(value = "adminContacts")
    private List<ObservedString> adminContacts;

    /*
     * The technicalContacts property.
     */
    @JsonProperty(value = "technicalContacts")
    private List<ObservedString> technicalContacts;

    /*
     * The alexaInfos property.
     */
    @JsonProperty(value = "alexaInfos")
    private List<AlexaInfo> alexaInfos;

    /*
     * The nameServers property.
     */
    @JsonProperty(value = "nameServers")
    private List<ObservedString> nameServers;

    /*
     * The mailServers property.
     */
    @JsonProperty(value = "mailServers")
    private List<ObservedString> mailServers;

    /*
     * The whoisServers property.
     */
    @JsonProperty(value = "whoisServers")
    private List<ObservedString> whoisServers;

    /*
     * The domainStatuses property.
     */
    @JsonProperty(value = "domainStatuses")
    private List<ObservedString> domainStatuses;

    /*
     * The registrarCreatedAt property.
     */
    @JsonProperty(value = "registrarCreatedAt")
    private List<ObservedLong> registrarCreatedAt;

    /*
     * The registrarUpdatedAt property.
     */
    @JsonProperty(value = "registrarUpdatedAt")
    private List<ObservedLong> registrarUpdatedAt;

    /*
     * The registrarExpiresAt property.
     */
    @JsonProperty(value = "registrarExpiresAt")
    private List<ObservedLong> registrarExpiresAt;

    /*
     * The soaRecords property.
     */
    @JsonProperty(value = "soaRecords")
    private List<SoaRecord> soaRecords;

    /*
     * The detailedFromWhoisAt property.
     */
    @JsonProperty(value = "detailedFromWhoisAt")
    private OffsetDateTime detailedFromWhoisAt;

    /*
     * The registrarNames property.
     */
    @JsonProperty(value = "registrarNames")
    private List<ObservedString> registrarNames;

    /*
     * The sources property.
     */
    @JsonProperty(value = "sources")
    private List<Source> sources;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The parkedDomain property.
     */
    @JsonProperty(value = "parkedDomain")
    private List<ObservedBoolean> parkedDomain;

    /*
     * The registrantNames property.
     */
    @JsonProperty(value = "registrantNames")
    private List<ObservedString> registrantNames;

    /*
     * The adminNames property.
     */
    @JsonProperty(value = "adminNames")
    private List<ObservedString> adminNames;

    /*
     * The technicalNames property.
     */
    @JsonProperty(value = "technicalNames")
    private List<ObservedString> technicalNames;

    /*
     * The adminOrgs property.
     */
    @JsonProperty(value = "adminOrgs")
    private List<ObservedString> adminOrgs;

    /*
     * The technicalOrgs property.
     */
    @JsonProperty(value = "technicalOrgs")
    private List<ObservedString> technicalOrgs;

    /*
     * The registrantPhones property.
     */
    @JsonProperty(value = "registrantPhones")
    private List<ObservedString> registrantPhones;

    /*
     * The adminPhones property.
     */
    @JsonProperty(value = "adminPhones")
    private List<ObservedString> adminPhones;

    /*
     * The technicalPhones property.
     */
    @JsonProperty(value = "technicalPhones")
    private List<ObservedString> technicalPhones;

    /** Creates an instance of DomainAsset class. */
    private DomainAsset() {}

    /**
     * Get the domain property: The domain property.
     *
     * @return the domain value.
     */
    public String getDomain() {
        return this.domain;
    }

    /**
     * Get the whoisId property: The whoisId property.
     *
     * @return the whoisId value.
     */
    public Long getWhoisId() {
        return this.whoisId;
    }

    /**
     * Get the registrarIanaIds property: The registrarIanaIds property.
     *
     * @return the registrarIanaIds value.
     */
    public List<ObservedInteger> getRegistrarIanaIds() {
        return this.registrarIanaIds;
    }

    /**
     * Get the registrantContacts property: The registrantContacts property.
     *
     * @return the registrantContacts value.
     */
    public List<ObservedString> getRegistrantContacts() {
        return this.registrantContacts;
    }

    /**
     * Get the registrantOrgs property: The registrantOrgs property.
     *
     * @return the registrantOrgs value.
     */
    public List<ObservedString> getRegistrantOrgs() {
        return this.registrantOrgs;
    }

    /**
     * Get the adminContacts property: The adminContacts property.
     *
     * @return the adminContacts value.
     */
    public List<ObservedString> getAdminContacts() {
        return this.adminContacts;
    }

    /**
     * Get the technicalContacts property: The technicalContacts property.
     *
     * @return the technicalContacts value.
     */
    public List<ObservedString> getTechnicalContacts() {
        return this.technicalContacts;
    }

    /**
     * Get the alexaInfos property: The alexaInfos property.
     *
     * @return the alexaInfos value.
     */
    public List<AlexaInfo> getAlexaInfos() {
        return this.alexaInfos;
    }

    /**
     * Get the nameServers property: The nameServers property.
     *
     * @return the nameServers value.
     */
    public List<ObservedString> getNameServers() {
        return this.nameServers;
    }

    /**
     * Get the mailServers property: The mailServers property.
     *
     * @return the mailServers value.
     */
    public List<ObservedString> getMailServers() {
        return this.mailServers;
    }

    /**
     * Get the whoisServers property: The whoisServers property.
     *
     * @return the whoisServers value.
     */
    public List<ObservedString> getWhoisServers() {
        return this.whoisServers;
    }

    /**
     * Get the domainStatuses property: The domainStatuses property.
     *
     * @return the domainStatuses value.
     */
    public List<ObservedString> getDomainStatuses() {
        return this.domainStatuses;
    }

    /**
     * Get the registrarCreatedAt property: The registrarCreatedAt property.
     *
     * @return the registrarCreatedAt value.
     */
    public List<ObservedLong> getRegistrarCreatedAt() {
        return this.registrarCreatedAt;
    }

    /**
     * Get the registrarUpdatedAt property: The registrarUpdatedAt property.
     *
     * @return the registrarUpdatedAt value.
     */
    public List<ObservedLong> getRegistrarUpdatedAt() {
        return this.registrarUpdatedAt;
    }

    /**
     * Get the registrarExpiresAt property: The registrarExpiresAt property.
     *
     * @return the registrarExpiresAt value.
     */
    public List<ObservedLong> getRegistrarExpiresAt() {
        return this.registrarExpiresAt;
    }

    /**
     * Get the soaRecords property: The soaRecords property.
     *
     * @return the soaRecords value.
     */
    public List<SoaRecord> getSoaRecords() {
        return this.soaRecords;
    }

    /**
     * Get the detailedFromWhoisAt property: The detailedFromWhoisAt property.
     *
     * @return the detailedFromWhoisAt value.
     */
    public OffsetDateTime getDetailedFromWhoisAt() {
        return this.detailedFromWhoisAt;
    }

    /**
     * Get the registrarNames property: The registrarNames property.
     *
     * @return the registrarNames value.
     */
    public List<ObservedString> getRegistrarNames() {
        return this.registrarNames;
    }

    /**
     * Get the sources property: The sources property.
     *
     * @return the sources value.
     */
    public List<Source> getSources() {
        return this.sources;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the parkedDomain property: The parkedDomain property.
     *
     * @return the parkedDomain value.
     */
    public List<ObservedBoolean> getParkedDomain() {
        return this.parkedDomain;
    }

    /**
     * Get the registrantNames property: The registrantNames property.
     *
     * @return the registrantNames value.
     */
    public List<ObservedString> getRegistrantNames() {
        return this.registrantNames;
    }

    /**
     * Get the adminNames property: The adminNames property.
     *
     * @return the adminNames value.
     */
    public List<ObservedString> getAdminNames() {
        return this.adminNames;
    }

    /**
     * Get the technicalNames property: The technicalNames property.
     *
     * @return the technicalNames value.
     */
    public List<ObservedString> getTechnicalNames() {
        return this.technicalNames;
    }

    /**
     * Get the adminOrgs property: The adminOrgs property.
     *
     * @return the adminOrgs value.
     */
    public List<ObservedString> getAdminOrgs() {
        return this.adminOrgs;
    }

    /**
     * Get the technicalOrgs property: The technicalOrgs property.
     *
     * @return the technicalOrgs value.
     */
    public List<ObservedString> getTechnicalOrgs() {
        return this.technicalOrgs;
    }

    /**
     * Get the registrantPhones property: The registrantPhones property.
     *
     * @return the registrantPhones value.
     */
    public List<ObservedString> getRegistrantPhones() {
        return this.registrantPhones;
    }

    /**
     * Get the adminPhones property: The adminPhones property.
     *
     * @return the adminPhones value.
     */
    public List<ObservedString> getAdminPhones() {
        return this.adminPhones;
    }

    /**
     * Get the technicalPhones property: The technicalPhones property.
     *
     * @return the technicalPhones value.
     */
    public List<ObservedString> getTechnicalPhones() {
        return this.technicalPhones;
    }
}
