// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** ErrorDetail. */
@Immutable
public final class ErrorDetail {
    /*
     * This is one of a server-defined set of error codes.
     */
    @JsonProperty(value = "code", required = true)
    private String code;

    /*
     * This is a human-readable representation of the error.
     */
    @JsonProperty(value = "message", required = true)
    private String message;

    /*
     * This is the error target.
     */
    @JsonProperty(value = "target")
    private String target;

    /*
     * This is an array of details about specific errors that led to this reported error.
     */
    @JsonProperty(value = "details")
    private List<ErrorDetail> details;

    /*
     * The innererror property.
     */
    @JsonProperty(value = "innererror", required = true)
    private InnerError innererror;

    /**
     * Creates an instance of ErrorDetail class.
     *
     * @param code the code value to set.
     * @param message the message value to set.
     * @param innererror the innererror value to set.
     */
    @JsonCreator
    private ErrorDetail(
            @JsonProperty(value = "code", required = true) String code,
            @JsonProperty(value = "message", required = true) String message,
            @JsonProperty(value = "innererror", required = true) InnerError innererror) {
        this.code = code;
        this.message = message;
        this.innererror = innererror;
    }

    /**
     * Get the code property: This is one of a server-defined set of error codes.
     *
     * @return the code value.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Get the message property: This is a human-readable representation of the error.
     *
     * @return the message value.
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * Get the target property: This is the error target.
     *
     * @return the target value.
     */
    public String getTarget() {
        return this.target;
    }

    /**
     * Get the details property: This is an array of details about specific errors that led to this reported error.
     *
     * @return the details value.
     */
    public List<ErrorDetail> getDetails() {
        return this.details;
    }

    /**
     * Get the innererror property: The innererror property.
     *
     * @return the innererror value.
     */
    public InnerError getInnererror() {
        return this.innererror;
    }
}
