// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** GuidPair. */
@Immutable
public final class GuidPair {
    /*
     * The pageGuid property.
     */
    @JsonProperty(value = "pageGuid")
    private String pageGuid;

    /*
     * The crawlStateGuid property.
     */
    @JsonProperty(value = "crawlStateGuid")
    private String crawlStateGuid;

    /*
     * The loadDate property.
     */
    @JsonProperty(value = "loadDate")
    private OffsetDateTime loadDate;

    /*
     * The recent property.
     */
    @JsonProperty(value = "recent")
    private Boolean recent;

    /** Creates an instance of GuidPair class. */
    private GuidPair() {}

    /**
     * Get the pageGuid property: The pageGuid property.
     *
     * @return the pageGuid value.
     */
    public String getPageGuid() {
        return this.pageGuid;
    }

    /**
     * Get the crawlStateGuid property: The crawlStateGuid property.
     *
     * @return the crawlStateGuid value.
     */
    public String getCrawlStateGuid() {
        return this.crawlStateGuid;
    }

    /**
     * Get the loadDate property: The loadDate property.
     *
     * @return the loadDate value.
     */
    public OffsetDateTime getLoadDate() {
        return this.loadDate;
    }

    /**
     * Get the recent property: The recent property.
     *
     * @return the recent value.
     */
    public Boolean isRecent() {
        return this.recent;
    }
}
