// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** HostAsset. */
@Immutable
public final class HostAsset {
    /*
     * The host property.
     */
    @JsonProperty(value = "host")
    private String host;

    /*
     * The domain property.
     */
    @JsonProperty(value = "domain")
    private String domain;

    /*
     * The ipAddresses property.
     */
    @JsonProperty(value = "ipAddresses")
    private List<ObservedString> ipAddresses;

    /*
     * The webComponents property.
     */
    @JsonProperty(value = "webComponents")
    private List<WebComponent> webComponents;

    /*
     * The headers property.
     */
    @JsonProperty(value = "headers")
    private List<ObservedHeader> headers;

    /*
     * The attributes property.
     */
    @JsonProperty(value = "attributes")
    private List<Attribute> attributes;

    /*
     * The cookies property.
     */
    @JsonProperty(value = "cookies")
    private List<Cookie> cookies;

    /*
     * The sslCerts property.
     */
    @JsonProperty(value = "sslCerts")
    private List<SslCertAsset> sslCerts;

    /*
     * The parentHosts property.
     */
    @JsonProperty(value = "parentHosts")
    private List<ObservedString> parentHosts;

    /*
     * The childHosts property.
     */
    @JsonProperty(value = "childHosts")
    private List<ObservedString> childHosts;

    /*
     * The hostCore property.
     */
    @JsonProperty(value = "hostCore", required = true)
    private HostCore hostCore;

    /*
     * The services property.
     */
    @JsonProperty(value = "services")
    private List<Service> services;

    /*
     * The cnames property.
     */
    @JsonProperty(value = "cnames")
    private List<ObservedString> cnames;

    /*
     * The sources property.
     */
    @JsonProperty(value = "sources")
    private List<Source> sources;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The resourceUrls property.
     */
    @JsonProperty(value = "resourceUrls")
    private List<ResourceUrl> resourceUrls;

    /*
     * The scanMetadata property.
     */
    @JsonProperty(value = "scanMetadata")
    private List<ScanMetadata> scanMetadata;

    /*
     * The asns property.
     */
    @JsonProperty(value = "asns")
    private List<ObservedLong> asns;

    /*
     * The ipBlocks property.
     */
    @JsonProperty(value = "ipBlocks")
    private List<IpBlock> ipBlocks;

    /*
     * The responseBodies property.
     */
    @JsonProperty(value = "responseBodies")
    private List<ObservedString> responseBodies;

    /*
     * The domainAsset property.
     */
    @JsonProperty(value = "domainAsset", required = true)
    private DomainAsset domainAsset;

    /*
     * The nsRecord property.
     */
    @JsonProperty(value = "nsRecord")
    private List<ObservedBoolean> nsRecord;

    /*
     * The mxRecord property.
     */
    @JsonProperty(value = "mxRecord")
    private List<ObservedBoolean> mxRecord;

    /*
     * The webserver property.
     */
    @JsonProperty(value = "webserver")
    private List<ObservedBoolean> webserver;

    /*
     * The location property.
     */
    @JsonProperty(value = "location")
    private List<ObservedLocation> location;

    /*
     * The nxdomain property.
     */
    @JsonProperty(value = "nxdomain")
    private List<ObservedBoolean> nxdomain;

    /*
     * The sslServerConfig property.
     */
    @JsonProperty(value = "sslServerConfig")
    private List<SslServerConfig> sslServerConfig;

    /*
     * The isWildcard property.
     */
    @JsonProperty(value = "isWildcard")
    private List<ObservedBoolean> isWildcard;

    /*
     * The banners property.
     */
    @JsonProperty(value = "banners")
    private List<Banner> banners;

    /*
     * The ipv4 property.
     */
    @JsonProperty(value = "ipv4")
    private List<ObservedBoolean> ipv4;

    /*
     * The ipv6 property.
     */
    @JsonProperty(value = "ipv6")
    private List<ObservedBoolean> ipv6;

    /**
     * Creates an instance of HostAsset class.
     *
     * @param hostCore the hostCore value to set.
     * @param domainAsset the domainAsset value to set.
     */
    @JsonCreator
    private HostAsset(
            @JsonProperty(value = "hostCore", required = true) HostCore hostCore,
            @JsonProperty(value = "domainAsset", required = true) DomainAsset domainAsset) {
        this.hostCore = hostCore;
        this.domainAsset = domainAsset;
    }

    /**
     * Get the host property: The host property.
     *
     * @return the host value.
     */
    public String getHost() {
        return this.host;
    }

    /**
     * Get the domain property: The domain property.
     *
     * @return the domain value.
     */
    public String getDomain() {
        return this.domain;
    }

    /**
     * Get the ipAddresses property: The ipAddresses property.
     *
     * @return the ipAddresses value.
     */
    public List<ObservedString> getIpAddresses() {
        return this.ipAddresses;
    }

    /**
     * Get the webComponents property: The webComponents property.
     *
     * @return the webComponents value.
     */
    public List<WebComponent> getWebComponents() {
        return this.webComponents;
    }

    /**
     * Get the headers property: The headers property.
     *
     * @return the headers value.
     */
    public List<ObservedHeader> getHeaders() {
        return this.headers;
    }

    /**
     * Get the attributes property: The attributes property.
     *
     * @return the attributes value.
     */
    public List<Attribute> getAttributes() {
        return this.attributes;
    }

    /**
     * Get the cookies property: The cookies property.
     *
     * @return the cookies value.
     */
    public List<Cookie> getCookies() {
        return this.cookies;
    }

    /**
     * Get the sslCerts property: The sslCerts property.
     *
     * @return the sslCerts value.
     */
    public List<SslCertAsset> getSslCerts() {
        return this.sslCerts;
    }

    /**
     * Get the parentHosts property: The parentHosts property.
     *
     * @return the parentHosts value.
     */
    public List<ObservedString> getParentHosts() {
        return this.parentHosts;
    }

    /**
     * Get the childHosts property: The childHosts property.
     *
     * @return the childHosts value.
     */
    public List<ObservedString> getChildHosts() {
        return this.childHosts;
    }

    /**
     * Get the hostCore property: The hostCore property.
     *
     * @return the hostCore value.
     */
    public HostCore getHostCore() {
        return this.hostCore;
    }

    /**
     * Get the services property: The services property.
     *
     * @return the services value.
     */
    public List<Service> getServices() {
        return this.services;
    }

    /**
     * Get the cnames property: The cnames property.
     *
     * @return the cnames value.
     */
    public List<ObservedString> getCnames() {
        return this.cnames;
    }

    /**
     * Get the sources property: The sources property.
     *
     * @return the sources value.
     */
    public List<Source> getSources() {
        return this.sources;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the resourceUrls property: The resourceUrls property.
     *
     * @return the resourceUrls value.
     */
    public List<ResourceUrl> getResourceUrls() {
        return this.resourceUrls;
    }

    /**
     * Get the scanMetadata property: The scanMetadata property.
     *
     * @return the scanMetadata value.
     */
    public List<ScanMetadata> getScanMetadata() {
        return this.scanMetadata;
    }

    /**
     * Get the asns property: The asns property.
     *
     * @return the asns value.
     */
    public List<ObservedLong> getAsns() {
        return this.asns;
    }

    /**
     * Get the ipBlocks property: The ipBlocks property.
     *
     * @return the ipBlocks value.
     */
    public List<IpBlock> getIpBlocks() {
        return this.ipBlocks;
    }

    /**
     * Get the responseBodies property: The responseBodies property.
     *
     * @return the responseBodies value.
     */
    public List<ObservedString> getResponseBodies() {
        return this.responseBodies;
    }

    /**
     * Get the domainAsset property: The domainAsset property.
     *
     * @return the domainAsset value.
     */
    public DomainAsset getDomainAsset() {
        return this.domainAsset;
    }

    /**
     * Get the nsRecord property: The nsRecord property.
     *
     * @return the nsRecord value.
     */
    public List<ObservedBoolean> getNsRecord() {
        return this.nsRecord;
    }

    /**
     * Get the mxRecord property: The mxRecord property.
     *
     * @return the mxRecord value.
     */
    public List<ObservedBoolean> getMxRecord() {
        return this.mxRecord;
    }

    /**
     * Get the webserver property: The webserver property.
     *
     * @return the webserver value.
     */
    public List<ObservedBoolean> getWebserver() {
        return this.webserver;
    }

    /**
     * Get the location property: The location property.
     *
     * @return the location value.
     */
    public List<ObservedLocation> getLocation() {
        return this.location;
    }

    /**
     * Get the nxdomain property: The nxdomain property.
     *
     * @return the nxdomain value.
     */
    public List<ObservedBoolean> getNxdomain() {
        return this.nxdomain;
    }

    /**
     * Get the sslServerConfig property: The sslServerConfig property.
     *
     * @return the sslServerConfig value.
     */
    public List<SslServerConfig> getSslServerConfig() {
        return this.sslServerConfig;
    }

    /**
     * Get the isWildcard property: The isWildcard property.
     *
     * @return the isWildcard value.
     */
    public List<ObservedBoolean> getIsWildcard() {
        return this.isWildcard;
    }

    /**
     * Get the banners property: The banners property.
     *
     * @return the banners value.
     */
    public List<Banner> getBanners() {
        return this.banners;
    }

    /**
     * Get the ipv4 property: The ipv4 property.
     *
     * @return the ipv4 value.
     */
    public List<ObservedBoolean> getIpv4() {
        return this.ipv4;
    }

    /**
     * Get the ipv6 property: The ipv6 property.
     *
     * @return the ipv6 value.
     */
    public List<ObservedBoolean> getIpv6() {
        return this.ipv6;
    }
}
