// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** HostCore. */
@Immutable
public final class HostCore {
    /*
     * The host property.
     */
    @JsonProperty(value = "host")
    private String host;

    /*
     * The domain property.
     */
    @JsonProperty(value = "domain")
    private String domain;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The blacklistCauseFirstSeen property.
     */
    @JsonProperty(value = "blacklistCauseFirstSeen")
    private OffsetDateTime blacklistCauseFirstSeen;

    /*
     * The blacklistCauseLastSeen property.
     */
    @JsonProperty(value = "blacklistCauseLastSeen")
    private OffsetDateTime blacklistCauseLastSeen;

    /*
     * The blacklistCauseCount property.
     */
    @JsonProperty(value = "blacklistCauseCount")
    private Long blacklistCauseCount;

    /*
     * The blacklistResourceFirstSeen property.
     */
    @JsonProperty(value = "blacklistResourceFirstSeen")
    private OffsetDateTime blacklistResourceFirstSeen;

    /*
     * The blacklistResourceLastSeen property.
     */
    @JsonProperty(value = "blacklistResourceLastSeen")
    private OffsetDateTime blacklistResourceLastSeen;

    /*
     * The blacklistResourceCount property.
     */
    @JsonProperty(value = "blacklistResourceCount")
    private Long blacklistResourceCount;

    /*
     * The blacklistSequenceFirstSeen property.
     */
    @JsonProperty(value = "blacklistSequenceFirstSeen")
    private OffsetDateTime blacklistSequenceFirstSeen;

    /*
     * The blacklistSequenceLastSeen property.
     */
    @JsonProperty(value = "blacklistSequenceLastSeen")
    private OffsetDateTime blacklistSequenceLastSeen;

    /*
     * The blacklistSequenceCount property.
     */
    @JsonProperty(value = "blacklistSequenceCount")
    private Long blacklistSequenceCount;

    /*
     * The phishCauseCount property.
     */
    @JsonProperty(value = "phishCauseCount")
    private Long phishCauseCount;

    /*
     * The malwareCauseCount property.
     */
    @JsonProperty(value = "malwareCauseCount")
    private Long malwareCauseCount;

    /*
     * The spamCauseCount property.
     */
    @JsonProperty(value = "spamCauseCount")
    private Long spamCauseCount;

    /*
     * The scamCauseCount property.
     */
    @JsonProperty(value = "scamCauseCount")
    private Long scamCauseCount;

    /*
     * The phishResourceCount property.
     */
    @JsonProperty(value = "phishResourceCount")
    private Long phishResourceCount;

    /*
     * The malwareResourceCount property.
     */
    @JsonProperty(value = "malwareResourceCount")
    private Long malwareResourceCount;

    /*
     * The spamResourceCount property.
     */
    @JsonProperty(value = "spamResourceCount")
    private Long spamResourceCount;

    /*
     * The scamResourceCount property.
     */
    @JsonProperty(value = "scamResourceCount")
    private Long scamResourceCount;

    /*
     * The phishSequenceCount property.
     */
    @JsonProperty(value = "phishSequenceCount")
    private Long phishSequenceCount;

    /*
     * The malwareSequenceCount property.
     */
    @JsonProperty(value = "malwareSequenceCount")
    private Long malwareSequenceCount;

    /*
     * The spamSequenceCount property.
     */
    @JsonProperty(value = "spamSequenceCount")
    private Long spamSequenceCount;

    /*
     * The scamSequenceCount property.
     */
    @JsonProperty(value = "scamSequenceCount")
    private Long scamSequenceCount;

    /*
     * The alexaRank property.
     */
    @JsonProperty(value = "alexaRank")
    private Integer alexaRank;

    /*
     * The hostReputationScore property.
     */
    @JsonProperty(value = "hostReputationScore")
    private Integer hostReputationScore;

    /*
     * The hostPhishReputationScore property.
     */
    @JsonProperty(value = "hostPhishReputationScore")
    private Integer hostPhishReputationScore;

    /*
     * The hostMalwareReputationScore property.
     */
    @JsonProperty(value = "hostMalwareReputationScore")
    private Integer hostMalwareReputationScore;

    /*
     * The hostSpamReputationScore property.
     */
    @JsonProperty(value = "hostSpamReputationScore")
    private Integer hostSpamReputationScore;

    /*
     * The hostScamReputationScore property.
     */
    @JsonProperty(value = "hostScamReputationScore")
    private Integer hostScamReputationScore;

    /*
     * The domainReputationScore property.
     */
    @JsonProperty(value = "domainReputationScore")
    private Integer domainReputationScore;

    /*
     * The domainPhishReputationScore property.
     */
    @JsonProperty(value = "domainPhishReputationScore")
    private Integer domainPhishReputationScore;

    /*
     * The domainMalwareReputationScore property.
     */
    @JsonProperty(value = "domainMalwareReputationScore")
    private Integer domainMalwareReputationScore;

    /*
     * The domainSpamReputationScore property.
     */
    @JsonProperty(value = "domainSpamReputationScore")
    private Integer domainSpamReputationScore;

    /*
     * The domainScamReputationScore property.
     */
    @JsonProperty(value = "domainScamReputationScore")
    private Integer domainScamReputationScore;

    /*
     * The uuid property.
     */
    @JsonProperty(value = "uuid")
    private String uuid;

    /** Creates an instance of HostCore class. */
    private HostCore() {}

    /**
     * Get the host property: The host property.
     *
     * @return the host value.
     */
    public String getHost() {
        return this.host;
    }

    /**
     * Get the domain property: The domain property.
     *
     * @return the domain value.
     */
    public String getDomain() {
        return this.domain;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the blacklistCauseFirstSeen property: The blacklistCauseFirstSeen property.
     *
     * @return the blacklistCauseFirstSeen value.
     */
    public OffsetDateTime getBlacklistCauseFirstSeen() {
        return this.blacklistCauseFirstSeen;
    }

    /**
     * Get the blacklistCauseLastSeen property: The blacklistCauseLastSeen property.
     *
     * @return the blacklistCauseLastSeen value.
     */
    public OffsetDateTime getBlacklistCauseLastSeen() {
        return this.blacklistCauseLastSeen;
    }

    /**
     * Get the blacklistCauseCount property: The blacklistCauseCount property.
     *
     * @return the blacklistCauseCount value.
     */
    public Long getBlacklistCauseCount() {
        return this.blacklistCauseCount;
    }

    /**
     * Get the blacklistResourceFirstSeen property: The blacklistResourceFirstSeen property.
     *
     * @return the blacklistResourceFirstSeen value.
     */
    public OffsetDateTime getBlacklistResourceFirstSeen() {
        return this.blacklistResourceFirstSeen;
    }

    /**
     * Get the blacklistResourceLastSeen property: The blacklistResourceLastSeen property.
     *
     * @return the blacklistResourceLastSeen value.
     */
    public OffsetDateTime getBlacklistResourceLastSeen() {
        return this.blacklistResourceLastSeen;
    }

    /**
     * Get the blacklistResourceCount property: The blacklistResourceCount property.
     *
     * @return the blacklistResourceCount value.
     */
    public Long getBlacklistResourceCount() {
        return this.blacklistResourceCount;
    }

    /**
     * Get the blacklistSequenceFirstSeen property: The blacklistSequenceFirstSeen property.
     *
     * @return the blacklistSequenceFirstSeen value.
     */
    public OffsetDateTime getBlacklistSequenceFirstSeen() {
        return this.blacklistSequenceFirstSeen;
    }

    /**
     * Get the blacklistSequenceLastSeen property: The blacklistSequenceLastSeen property.
     *
     * @return the blacklistSequenceLastSeen value.
     */
    public OffsetDateTime getBlacklistSequenceLastSeen() {
        return this.blacklistSequenceLastSeen;
    }

    /**
     * Get the blacklistSequenceCount property: The blacklistSequenceCount property.
     *
     * @return the blacklistSequenceCount value.
     */
    public Long getBlacklistSequenceCount() {
        return this.blacklistSequenceCount;
    }

    /**
     * Get the phishCauseCount property: The phishCauseCount property.
     *
     * @return the phishCauseCount value.
     */
    public Long getPhishCauseCount() {
        return this.phishCauseCount;
    }

    /**
     * Get the malwareCauseCount property: The malwareCauseCount property.
     *
     * @return the malwareCauseCount value.
     */
    public Long getMalwareCauseCount() {
        return this.malwareCauseCount;
    }

    /**
     * Get the spamCauseCount property: The spamCauseCount property.
     *
     * @return the spamCauseCount value.
     */
    public Long getSpamCauseCount() {
        return this.spamCauseCount;
    }

    /**
     * Get the scamCauseCount property: The scamCauseCount property.
     *
     * @return the scamCauseCount value.
     */
    public Long getScamCauseCount() {
        return this.scamCauseCount;
    }

    /**
     * Get the phishResourceCount property: The phishResourceCount property.
     *
     * @return the phishResourceCount value.
     */
    public Long getPhishResourceCount() {
        return this.phishResourceCount;
    }

    /**
     * Get the malwareResourceCount property: The malwareResourceCount property.
     *
     * @return the malwareResourceCount value.
     */
    public Long getMalwareResourceCount() {
        return this.malwareResourceCount;
    }

    /**
     * Get the spamResourceCount property: The spamResourceCount property.
     *
     * @return the spamResourceCount value.
     */
    public Long getSpamResourceCount() {
        return this.spamResourceCount;
    }

    /**
     * Get the scamResourceCount property: The scamResourceCount property.
     *
     * @return the scamResourceCount value.
     */
    public Long getScamResourceCount() {
        return this.scamResourceCount;
    }

    /**
     * Get the phishSequenceCount property: The phishSequenceCount property.
     *
     * @return the phishSequenceCount value.
     */
    public Long getPhishSequenceCount() {
        return this.phishSequenceCount;
    }

    /**
     * Get the malwareSequenceCount property: The malwareSequenceCount property.
     *
     * @return the malwareSequenceCount value.
     */
    public Long getMalwareSequenceCount() {
        return this.malwareSequenceCount;
    }

    /**
     * Get the spamSequenceCount property: The spamSequenceCount property.
     *
     * @return the spamSequenceCount value.
     */
    public Long getSpamSequenceCount() {
        return this.spamSequenceCount;
    }

    /**
     * Get the scamSequenceCount property: The scamSequenceCount property.
     *
     * @return the scamSequenceCount value.
     */
    public Long getScamSequenceCount() {
        return this.scamSequenceCount;
    }

    /**
     * Get the alexaRank property: The alexaRank property.
     *
     * @return the alexaRank value.
     */
    public Integer getAlexaRank() {
        return this.alexaRank;
    }

    /**
     * Get the hostReputationScore property: The hostReputationScore property.
     *
     * @return the hostReputationScore value.
     */
    public Integer getHostReputationScore() {
        return this.hostReputationScore;
    }

    /**
     * Get the hostPhishReputationScore property: The hostPhishReputationScore property.
     *
     * @return the hostPhishReputationScore value.
     */
    public Integer getHostPhishReputationScore() {
        return this.hostPhishReputationScore;
    }

    /**
     * Get the hostMalwareReputationScore property: The hostMalwareReputationScore property.
     *
     * @return the hostMalwareReputationScore value.
     */
    public Integer getHostMalwareReputationScore() {
        return this.hostMalwareReputationScore;
    }

    /**
     * Get the hostSpamReputationScore property: The hostSpamReputationScore property.
     *
     * @return the hostSpamReputationScore value.
     */
    public Integer getHostSpamReputationScore() {
        return this.hostSpamReputationScore;
    }

    /**
     * Get the hostScamReputationScore property: The hostScamReputationScore property.
     *
     * @return the hostScamReputationScore value.
     */
    public Integer getHostScamReputationScore() {
        return this.hostScamReputationScore;
    }

    /**
     * Get the domainReputationScore property: The domainReputationScore property.
     *
     * @return the domainReputationScore value.
     */
    public Integer getDomainReputationScore() {
        return this.domainReputationScore;
    }

    /**
     * Get the domainPhishReputationScore property: The domainPhishReputationScore property.
     *
     * @return the domainPhishReputationScore value.
     */
    public Integer getDomainPhishReputationScore() {
        return this.domainPhishReputationScore;
    }

    /**
     * Get the domainMalwareReputationScore property: The domainMalwareReputationScore property.
     *
     * @return the domainMalwareReputationScore value.
     */
    public Integer getDomainMalwareReputationScore() {
        return this.domainMalwareReputationScore;
    }

    /**
     * Get the domainSpamReputationScore property: The domainSpamReputationScore property.
     *
     * @return the domainSpamReputationScore value.
     */
    public Integer getDomainSpamReputationScore() {
        return this.domainSpamReputationScore;
    }

    /**
     * Get the domainScamReputationScore property: The domainScamReputationScore property.
     *
     * @return the domainScamReputationScore value.
     */
    public Integer getDomainScamReputationScore() {
        return this.domainScamReputationScore;
    }

    /**
     * Get the uuid property: The uuid property.
     *
     * @return the uuid value.
     */
    public String getUuid() {
        return this.uuid;
    }
}
