// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/** InnerError. */
@Immutable
public final class InnerError {
    /*
     * This is a more specific error code than was provided by the containing error.
     */
    @JsonProperty(value = "code")
    private String code;

    /*
     * This is an additional field representing the value that caused the error to help with debugging.
     */
    @JsonProperty(value = "value")
    private Object value;

    /** Creates an instance of InnerError class. */
    private InnerError() {}

    /**
     * Get the code property: This is a more specific error code than was provided by the containing error.
     *
     * @return the code value.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Get the value property: This is an additional field representing the value that caused the error to help with
     * debugging.
     *
     * @return the value value.
     */
    public Object getValue() {
        return this.value;
    }
}
