// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Location. */
@Immutable
public final class Location {
    /*
     * The countryCode property.
     */
    @JsonProperty(value = "countryCode")
    private String countryCode;

    /*
     * The countryName property.
     */
    @JsonProperty(value = "countryName")
    private String countryName;

    /*
     * The region property.
     */
    @JsonProperty(value = "region")
    private String region;

    /*
     * The regionName property.
     */
    @JsonProperty(value = "regionName")
    private String regionName;

    /*
     * The city property.
     */
    @JsonProperty(value = "city")
    private String city;

    /*
     * The areaCode property.
     */
    @JsonProperty(value = "areaCode")
    private Integer areaCode;

    /*
     * The postalCode property.
     */
    @JsonProperty(value = "postalCode")
    private String postalCode;

    /*
     * The latitude property.
     */
    @JsonProperty(value = "latitude")
    private Double latitude;

    /*
     * The longitude property.
     */
    @JsonProperty(value = "longitude")
    private Double longitude;

    /*
     * The dmaCode property.
     */
    @JsonProperty(value = "dmaCode")
    private Integer dmaCode;

    /*
     * The metroCodeId property.
     */
    @JsonProperty(value = "metroCodeId")
    private Integer metroCodeId;

    /** Creates an instance of Location class. */
    private Location() {}

    /**
     * Get the countryCode property: The countryCode property.
     *
     * @return the countryCode value.
     */
    public String getCountryCode() {
        return this.countryCode;
    }

    /**
     * Get the countryName property: The countryName property.
     *
     * @return the countryName value.
     */
    public String getCountryName() {
        return this.countryName;
    }

    /**
     * Get the region property: The region property.
     *
     * @return the region value.
     */
    public String getRegion() {
        return this.region;
    }

    /**
     * Get the regionName property: The regionName property.
     *
     * @return the regionName value.
     */
    public String getRegionName() {
        return this.regionName;
    }

    /**
     * Get the city property: The city property.
     *
     * @return the city value.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Get the areaCode property: The areaCode property.
     *
     * @return the areaCode value.
     */
    public Integer getAreaCode() {
        return this.areaCode;
    }

    /**
     * Get the postalCode property: The postalCode property.
     *
     * @return the postalCode value.
     */
    public String getPostalCode() {
        return this.postalCode;
    }

    /**
     * Get the latitude property: The latitude property.
     *
     * @return the latitude value.
     */
    public Double getLatitude() {
        return this.latitude;
    }

    /**
     * Get the longitude property: The longitude property.
     *
     * @return the longitude value.
     */
    public Double getLongitude() {
        return this.longitude;
    }

    /**
     * Get the dmaCode property: The dmaCode property.
     *
     * @return the dmaCode value.
     */
    public Integer getDmaCode() {
        return this.dmaCode;
    }

    /**
     * Get the metroCodeId property: The metroCodeId property.
     *
     * @return the metroCodeId value.
     */
    public Integer getMetroCodeId() {
        return this.metroCodeId;
    }
}
