// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** LogAnalyticsDataConnectionProperties. */
@Fluent
public final class LogAnalyticsDataConnectionProperties {
    /*
     * log analytics api key
     */
    @JsonProperty(value = "apiKey")
    private String apiKey;

    /*
     * log analytics workspace id
     */
    @JsonProperty(value = "workspaceId")
    private String workspaceId;

    /** Creates an instance of LogAnalyticsDataConnectionProperties class. */
    public LogAnalyticsDataConnectionProperties() {}

    /**
     * Get the apiKey property: log analytics api key.
     *
     * @return the apiKey value.
     */
    public String getApiKey() {
        return this.apiKey;
    }

    /**
     * Set the apiKey property: log analytics api key.
     *
     * @param apiKey the apiKey value to set.
     * @return the LogAnalyticsDataConnectionProperties object itself.
     */
    public LogAnalyticsDataConnectionProperties setApiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }

    /**
     * Get the workspaceId property: log analytics workspace id.
     *
     * @return the workspaceId value.
     */
    public String getWorkspaceId() {
        return this.workspaceId;
    }

    /**
     * Set the workspaceId property: log analytics workspace id.
     *
     * @param workspaceId the workspaceId value to set.
     * @return the LogAnalyticsDataConnectionProperties object itself.
     */
    public LogAnalyticsDataConnectionProperties setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
}
