// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The LogAnalyticsDataConnectionResponse model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("logAnalytics")
@Immutable
public final class LogAnalyticsDataConnectionResponse extends DataConnectionResponse {
    /*
     * The properties property.
     */
    @JsonProperty(value = "properties", required = true)
    private LogAnalyticsDataConnectionProperties properties;

    /**
     * Creates an instance of LogAnalyticsDataConnectionResponse class.
     *
     * @param properties the properties value to set.
     * @param properties the properties value to set.
     */
    @JsonCreator
    private LogAnalyticsDataConnectionResponse(
            @JsonProperty(value = "properties", required = true) Object properties,
            @JsonProperty(value = "properties", required = true) LogAnalyticsDataConnectionProperties properties) {
        super(properties);
        this.properties = properties;
    }

    /**
     * Get the properties property: The properties property.
     *
     * @return the properties value.
     */
    public LogAnalyticsDataConnectionProperties getProperties() {
        return this.properties;
    }
}
