// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for ObservedPortStateValue. */
public final class ObservedPortStateValue extends ExpandableStringEnum<ObservedPortStateValue> {
    /** Static value open for ObservedPortStateValue. */
    public static final ObservedPortStateValue OPEN = fromString("open");

    /** Static value closed for ObservedPortStateValue. */
    public static final ObservedPortStateValue CLOSED = fromString("closed");

    /** Static value filtered for ObservedPortStateValue. */
    public static final ObservedPortStateValue FILTERED = fromString("filtered");

    /**
     * Creates a new instance of ObservedPortStateValue value.
     *
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public ObservedPortStateValue() {}

    /**
     * Creates or finds a ObservedPortStateValue from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding ObservedPortStateValue.
     */
    @JsonCreator
    public static ObservedPortStateValue fromString(String name) {
        return fromString(name, ObservedPortStateValue.class);
    }

    /**
     * Gets known ObservedPortStateValue values.
     *
     * @return known ObservedPortStateValue values.
     */
    public static Collection<ObservedPortStateValue> values() {
        return values(ObservedPortStateValue.class);
    }
}
