// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** ObservedHeader. */
@Immutable
public final class ObservedHeader {
    /*
     * The headerName property.
     */
    @JsonProperty(value = "headerName")
    private String headerName;

    /*
     * The headerValue property.
     */
    @JsonProperty(value = "headerValue")
    private String headerValue;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The recent property.
     */
    @JsonProperty(value = "recent")
    private Boolean recent;

    /** Creates an instance of ObservedHeader class. */
    private ObservedHeader() {}

    /**
     * Get the headerName property: The headerName property.
     *
     * @return the headerName value.
     */
    public String getHeaderName() {
        return this.headerName;
    }

    /**
     * Get the headerValue property: The headerValue property.
     *
     * @return the headerValue value.
     */
    public String getHeaderValue() {
        return this.headerValue;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the recent property: The recent property.
     *
     * @return the recent value.
     */
    public Boolean isRecent() {
        return this.recent;
    }
}
