// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** ObservedPortState. */
@Immutable
public final class ObservedPortState {
    /*
     * The value property.
     */
    @JsonProperty(value = "value")
    private ObservedPortStateValue value;

    /*
     * The port property.
     */
    @JsonProperty(value = "port")
    private Integer port;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The recent property.
     */
    @JsonProperty(value = "recent")
    private Boolean recent;

    /** Creates an instance of ObservedPortState class. */
    private ObservedPortState() {}

    /**
     * Get the value property: The value property.
     *
     * @return the value value.
     */
    public ObservedPortStateValue getValue() {
        return this.value;
    }

    /**
     * Get the port property: The port property.
     *
     * @return the port value.
     */
    public Integer getPort() {
        return this.port;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the recent property: The recent property.
     *
     * @return the recent value.
     */
    public Boolean isRecent() {
        return this.recent;
    }
}
