// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for PageAssetRedirectType. */
public final class PageAssetRedirectType extends ExpandableStringEnum<PageAssetRedirectType> {
    /** Static value httpHeader for PageAssetRedirectType. */
    public static final PageAssetRedirectType HTTP_HEADER = fromString("httpHeader");

    /** Static value metaRefresh for PageAssetRedirectType. */
    public static final PageAssetRedirectType META_REFRESH = fromString("metaRefresh");

    /** Static value javascript for PageAssetRedirectType. */
    public static final PageAssetRedirectType JAVASCRIPT = fromString("javascript");

    /** Static value final for PageAssetRedirectType. */
    public static final PageAssetRedirectType FINAL = fromString("final");

    /**
     * Creates a new instance of PageAssetRedirectType value.
     *
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public PageAssetRedirectType() {}

    /**
     * Creates or finds a PageAssetRedirectType from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding PageAssetRedirectType.
     */
    @JsonCreator
    public static PageAssetRedirectType fromString(String name) {
        return fromString(name, PageAssetRedirectType.class);
    }

    /**
     * Gets known PageAssetRedirectType values.
     *
     * @return known PageAssetRedirectType values.
     */
    public static Collection<PageAssetRedirectType> values() {
        return values(PageAssetRedirectType.class);
    }
}
