// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/** PageCause. */
@Immutable
public final class PageCause {
    /*
     * The cause property.
     */
    @JsonProperty(value = "cause")
    private String cause;

    /*
     * The causeElementXPath property.
     */
    @JsonProperty(value = "causeElementXPath")
    private String causeElementXPath;

    /*
     * The location property.
     */
    @JsonProperty(value = "location")
    private String location;

    /*
     * The possibleMatches property.
     */
    @JsonProperty(value = "possibleMatches")
    private Integer possibleMatches;

    /*
     * The loopDetected property.
     */
    @JsonProperty(value = "loopDetected")
    private Boolean loopDetected;

    /*
     * The version property.
     */
    @JsonProperty(value = "version")
    private Integer version;

    /*
     * The domChangeIndex property.
     */
    @JsonProperty(value = "domChangeIndex")
    private Integer domChangeIndex;

    /** Creates an instance of PageCause class. */
    private PageCause() {}

    /**
     * Get the cause property: The cause property.
     *
     * @return the cause value.
     */
    public String getCause() {
        return this.cause;
    }

    /**
     * Get the causeElementXPath property: The causeElementXPath property.
     *
     * @return the causeElementXPath value.
     */
    public String getCauseElementXPath() {
        return this.causeElementXPath;
    }

    /**
     * Get the location property: The location property.
     *
     * @return the location value.
     */
    public String getLocation() {
        return this.location;
    }

    /**
     * Get the possibleMatches property: The possibleMatches property.
     *
     * @return the possibleMatches value.
     */
    public Integer getPossibleMatches() {
        return this.possibleMatches;
    }

    /**
     * Get the loopDetected property: The loopDetected property.
     *
     * @return the loopDetected value.
     */
    public Boolean isLoopDetected() {
        return this.loopDetected;
    }

    /**
     * Get the version property: The version property.
     *
     * @return the version value.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Get the domChangeIndex property: The domChangeIndex property.
     *
     * @return the domChangeIndex value.
     */
    public Integer getDomChangeIndex() {
        return this.domChangeIndex;
    }
}
