// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** PageAsset. */
@Immutable
public final class PageAsset {
    /*
     * The url property.
     */
    @JsonProperty(value = "url")
    private String url;

    /*
     * The httpMethod property.
     */
    @JsonProperty(value = "httpMethod")
    private String httpMethod;

    /*
     * The service property.
     */
    @JsonProperty(value = "service")
    private String service;

    /*
     * The ipAddresses property.
     */
    @JsonProperty(value = "ipAddresses")
    private List<ObservedString> ipAddresses;

    /*
     * The successful property.
     */
    @JsonProperty(value = "successful")
    private List<ObservedBoolean> successful;

    /*
     * The httpResponseCodes property.
     */
    @JsonProperty(value = "httpResponseCodes")
    private List<ObservedInteger> httpResponseCodes;

    /*
     * The httpResponseMessages property.
     */
    @JsonProperty(value = "httpResponseMessages")
    private List<ObservedString> httpResponseMessages;

    /*
     * The responseTimes property.
     */
    @JsonProperty(value = "responseTimes")
    private List<ObservedLong> responseTimes;

    /*
     * The frames property.
     */
    @JsonProperty(value = "frames")
    private List<ObservedBoolean> frames;

    /*
     * The windows property.
     */
    @JsonProperty(value = "windows")
    private List<ObservedBoolean> windows;

    /*
     * The nonHtmlFrames property.
     */
    @JsonProperty(value = "nonHtmlFrames")
    private List<ObservedBoolean> nonHtmlFrames;

    /*
     * The undirectedContent property.
     */
    @JsonProperty(value = "undirectedContent")
    private List<ObservedBoolean> undirectedContent;

    /*
     * The contentTypes property.
     */
    @JsonProperty(value = "contentTypes")
    private List<ObservedString> contentTypes;

    /*
     * The contentLengths property.
     */
    @JsonProperty(value = "contentLengths")
    private List<ObservedLong> contentLengths;

    /*
     * The windowNames property.
     */
    @JsonProperty(value = "windowNames")
    private List<ObservedString> windowNames;

    /*
     * The charsets property.
     */
    @JsonProperty(value = "charsets")
    private List<ObservedString> charsets;

    /*
     * The titles property.
     */
    @JsonProperty(value = "titles")
    private List<ObservedString> titles;

    /*
     * The languages property.
     */
    @JsonProperty(value = "languages")
    private List<ObservedString> languages;

    /*
     * The responseHeaders property.
     */
    @JsonProperty(value = "responseHeaders")
    private List<ObservedHeader> responseHeaders;

    /*
     * The cookies property.
     */
    @JsonProperty(value = "cookies")
    private List<Cookie> cookies;

    /*
     * The webComponents property.
     */
    @JsonProperty(value = "webComponents")
    private List<WebComponent> webComponents;

    /*
     * The attributes property.
     */
    @JsonProperty(value = "attributes")
    private List<Attribute> attributes;

    /*
     * The assetSecurityPolicies property.
     */
    @JsonProperty(value = "assetSecurityPolicies")
    private List<AssetSecurityPolicy> assetSecurityPolicies;

    /*
     * The responseBodyMinhashSignatures property.
     */
    @JsonProperty(value = "responseBodyMinhashSignatures")
    private List<ObservedIntegers> responseBodyMinhashSignatures;

    /*
     * The fullDomMinhashSignatures property.
     */
    @JsonProperty(value = "fullDomMinhashSignatures")
    private List<ObservedIntegers> fullDomMinhashSignatures;

    /*
     * The responseBodyHashSignatures property.
     */
    @JsonProperty(value = "responseBodyHashSignatures")
    private List<ObservedString> responseBodyHashSignatures;

    /*
     * The errors property.
     */
    @JsonProperty(value = "errors")
    private List<ObservedString> errors;

    /*
     * The sslCerts property.
     */
    @JsonProperty(value = "sslCerts")
    private List<SslCertAsset> sslCerts;

    /*
     * The sources property.
     */
    @JsonProperty(value = "sources")
    private List<Source> sources;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The cause property.
     */
    @JsonProperty(value = "cause", required = true)
    private PageCause cause;

    /*
     * The referrer property.
     */
    @JsonProperty(value = "referrer")
    private String referrer;

    /*
     * The redirectUrls property.
     */
    @JsonProperty(value = "redirectUrls")
    private List<ObservedString> redirectUrls;

    /*
     * The redirectType property.
     */
    @JsonProperty(value = "redirectType")
    private PageAssetRedirectType redirectType;

    /*
     * The finalUrls property.
     */
    @JsonProperty(value = "finalUrls")
    private List<ObservedString> finalUrls;

    /*
     * The finalResponseCodes property.
     */
    @JsonProperty(value = "finalResponseCodes")
    private List<ObservedInteger> finalResponseCodes;

    /*
     * The parkedPage property.
     */
    @JsonProperty(value = "parkedPage")
    private List<ObservedBoolean> parkedPage;

    /*
     * The resourceUrls property.
     */
    @JsonProperty(value = "resourceUrls")
    private List<ResourceUrl> resourceUrls;

    /*
     * The guids property.
     */
    @JsonProperty(value = "guids")
    private List<GuidPair> guids;

    /*
     * The finalIpAddresses property.
     */
    @JsonProperty(value = "finalIpAddresses")
    private List<ObservedString> finalIpAddresses;

    /*
     * The asns property.
     */
    @JsonProperty(value = "asns")
    private List<ObservedLong> asns;

    /*
     * The ipBlocks property.
     */
    @JsonProperty(value = "ipBlocks")
    private List<IpBlock> ipBlocks;

    /*
     * The finalAsns property.
     */
    @JsonProperty(value = "finalAsns")
    private List<ObservedLong> finalAsns;

    /*
     * The finalIpBlocks property.
     */
    @JsonProperty(value = "finalIpBlocks")
    private List<IpBlock> finalIpBlocks;

    /*
     * The responseBodies property.
     */
    @JsonProperty(value = "responseBodies")
    private List<ObservedString> responseBodies;

    /*
     * The domainAsset property.
     */
    @JsonProperty(value = "domainAsset", required = true)
    private DomainAsset domainAsset;

    /*
     * The rootUrl property.
     */
    @JsonProperty(value = "rootUrl", required = true)
    private ObservedBoolean rootUrl;

    /*
     * The isRootUrl property.
     */
    @JsonProperty(value = "isRootUrl")
    private Boolean isRootUrl;

    /*
     * The location property.
     */
    @JsonProperty(value = "location")
    private List<ObservedLocation> location;

    /*
     * The services property.
     */
    @JsonProperty(value = "services")
    private List<Service> services;

    /*
     * The siteStatus property.
     */
    @JsonProperty(value = "siteStatus")
    private String siteStatus;

    /*
     * The cnames property.
     */
    @JsonProperty(value = "cnames")
    private List<ObservedString> cnames;

    /*
     * The cdns property.
     */
    @JsonProperty(value = "cdns")
    private List<ObservedString> cdns;

    /*
     * The host property.
     */
    @JsonProperty(value = "host")
    private String host;

    /*
     * The domain property.
     */
    @JsonProperty(value = "domain")
    private String domain;

    /*
     * The sslServerConfig property.
     */
    @JsonProperty(value = "sslServerConfig")
    private List<SslServerConfig> sslServerConfig;

    /*
     * The gdprAssetSecurityPolicies property.
     */
    @JsonProperty(value = "gdprAssetSecurityPolicies")
    private List<AssetSecurityPolicy> gdprAssetSecurityPolicies;

    /*
     * The ipv4 property.
     */
    @JsonProperty(value = "ipv4")
    private List<ObservedBoolean> ipv4;

    /*
     * The ipv6 property.
     */
    @JsonProperty(value = "ipv6")
    private List<ObservedBoolean> ipv6;

    /**
     * Creates an instance of PageAsset class.
     *
     * @param cause the cause value to set.
     * @param domainAsset the domainAsset value to set.
     * @param rootUrl the rootUrl value to set.
     */
    @JsonCreator
    private PageAsset(
            @JsonProperty(value = "cause", required = true) PageCause cause,
            @JsonProperty(value = "domainAsset", required = true) DomainAsset domainAsset,
            @JsonProperty(value = "rootUrl", required = true) ObservedBoolean rootUrl) {
        this.cause = cause;
        this.domainAsset = domainAsset;
        this.rootUrl = rootUrl;
    }

    /**
     * Get the url property: The url property.
     *
     * @return the url value.
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Get the httpMethod property: The httpMethod property.
     *
     * @return the httpMethod value.
     */
    public String getHttpMethod() {
        return this.httpMethod;
    }

    /**
     * Get the service property: The service property.
     *
     * @return the service value.
     */
    public String getService() {
        return this.service;
    }

    /**
     * Get the ipAddresses property: The ipAddresses property.
     *
     * @return the ipAddresses value.
     */
    public List<ObservedString> getIpAddresses() {
        return this.ipAddresses;
    }

    /**
     * Get the successful property: The successful property.
     *
     * @return the successful value.
     */
    public List<ObservedBoolean> getSuccessful() {
        return this.successful;
    }

    /**
     * Get the httpResponseCodes property: The httpResponseCodes property.
     *
     * @return the httpResponseCodes value.
     */
    public List<ObservedInteger> getHttpResponseCodes() {
        return this.httpResponseCodes;
    }

    /**
     * Get the httpResponseMessages property: The httpResponseMessages property.
     *
     * @return the httpResponseMessages value.
     */
    public List<ObservedString> getHttpResponseMessages() {
        return this.httpResponseMessages;
    }

    /**
     * Get the responseTimes property: The responseTimes property.
     *
     * @return the responseTimes value.
     */
    public List<ObservedLong> getResponseTimes() {
        return this.responseTimes;
    }

    /**
     * Get the frames property: The frames property.
     *
     * @return the frames value.
     */
    public List<ObservedBoolean> getFrames() {
        return this.frames;
    }

    /**
     * Get the windows property: The windows property.
     *
     * @return the windows value.
     */
    public List<ObservedBoolean> getWindows() {
        return this.windows;
    }

    /**
     * Get the nonHtmlFrames property: The nonHtmlFrames property.
     *
     * @return the nonHtmlFrames value.
     */
    public List<ObservedBoolean> getNonHtmlFrames() {
        return this.nonHtmlFrames;
    }

    /**
     * Get the undirectedContent property: The undirectedContent property.
     *
     * @return the undirectedContent value.
     */
    public List<ObservedBoolean> getUndirectedContent() {
        return this.undirectedContent;
    }

    /**
     * Get the contentTypes property: The contentTypes property.
     *
     * @return the contentTypes value.
     */
    public List<ObservedString> getContentTypes() {
        return this.contentTypes;
    }

    /**
     * Get the contentLengths property: The contentLengths property.
     *
     * @return the contentLengths value.
     */
    public List<ObservedLong> getContentLengths() {
        return this.contentLengths;
    }

    /**
     * Get the windowNames property: The windowNames property.
     *
     * @return the windowNames value.
     */
    public List<ObservedString> getWindowNames() {
        return this.windowNames;
    }

    /**
     * Get the charsets property: The charsets property.
     *
     * @return the charsets value.
     */
    public List<ObservedString> getCharsets() {
        return this.charsets;
    }

    /**
     * Get the titles property: The titles property.
     *
     * @return the titles value.
     */
    public List<ObservedString> getTitles() {
        return this.titles;
    }

    /**
     * Get the languages property: The languages property.
     *
     * @return the languages value.
     */
    public List<ObservedString> getLanguages() {
        return this.languages;
    }

    /**
     * Get the responseHeaders property: The responseHeaders property.
     *
     * @return the responseHeaders value.
     */
    public List<ObservedHeader> getResponseHeaders() {
        return this.responseHeaders;
    }

    /**
     * Get the cookies property: The cookies property.
     *
     * @return the cookies value.
     */
    public List<Cookie> getCookies() {
        return this.cookies;
    }

    /**
     * Get the webComponents property: The webComponents property.
     *
     * @return the webComponents value.
     */
    public List<WebComponent> getWebComponents() {
        return this.webComponents;
    }

    /**
     * Get the attributes property: The attributes property.
     *
     * @return the attributes value.
     */
    public List<Attribute> getAttributes() {
        return this.attributes;
    }

    /**
     * Get the assetSecurityPolicies property: The assetSecurityPolicies property.
     *
     * @return the assetSecurityPolicies value.
     */
    public List<AssetSecurityPolicy> getAssetSecurityPolicies() {
        return this.assetSecurityPolicies;
    }

    /**
     * Get the responseBodyMinhashSignatures property: The responseBodyMinhashSignatures property.
     *
     * @return the responseBodyMinhashSignatures value.
     */
    public List<ObservedIntegers> getResponseBodyMinhashSignatures() {
        return this.responseBodyMinhashSignatures;
    }

    /**
     * Get the fullDomMinhashSignatures property: The fullDomMinhashSignatures property.
     *
     * @return the fullDomMinhashSignatures value.
     */
    public List<ObservedIntegers> getFullDomMinhashSignatures() {
        return this.fullDomMinhashSignatures;
    }

    /**
     * Get the responseBodyHashSignatures property: The responseBodyHashSignatures property.
     *
     * @return the responseBodyHashSignatures value.
     */
    public List<ObservedString> getResponseBodyHashSignatures() {
        return this.responseBodyHashSignatures;
    }

    /**
     * Get the errors property: The errors property.
     *
     * @return the errors value.
     */
    public List<ObservedString> getErrors() {
        return this.errors;
    }

    /**
     * Get the sslCerts property: The sslCerts property.
     *
     * @return the sslCerts value.
     */
    public List<SslCertAsset> getSslCerts() {
        return this.sslCerts;
    }

    /**
     * Get the sources property: The sources property.
     *
     * @return the sources value.
     */
    public List<Source> getSources() {
        return this.sources;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the cause property: The cause property.
     *
     * @return the cause value.
     */
    public PageCause getCause() {
        return this.cause;
    }

    /**
     * Get the referrer property: The referrer property.
     *
     * @return the referrer value.
     */
    public String getReferrer() {
        return this.referrer;
    }

    /**
     * Get the redirectUrls property: The redirectUrls property.
     *
     * @return the redirectUrls value.
     */
    public List<ObservedString> getRedirectUrls() {
        return this.redirectUrls;
    }

    /**
     * Get the redirectType property: The redirectType property.
     *
     * @return the redirectType value.
     */
    public PageAssetRedirectType getRedirectType() {
        return this.redirectType;
    }

    /**
     * Get the finalUrls property: The finalUrls property.
     *
     * @return the finalUrls value.
     */
    public List<ObservedString> getFinalUrls() {
        return this.finalUrls;
    }

    /**
     * Get the finalResponseCodes property: The finalResponseCodes property.
     *
     * @return the finalResponseCodes value.
     */
    public List<ObservedInteger> getFinalResponseCodes() {
        return this.finalResponseCodes;
    }

    /**
     * Get the parkedPage property: The parkedPage property.
     *
     * @return the parkedPage value.
     */
    public List<ObservedBoolean> getParkedPage() {
        return this.parkedPage;
    }

    /**
     * Get the resourceUrls property: The resourceUrls property.
     *
     * @return the resourceUrls value.
     */
    public List<ResourceUrl> getResourceUrls() {
        return this.resourceUrls;
    }

    /**
     * Get the guids property: The guids property.
     *
     * @return the guids value.
     */
    public List<GuidPair> getGuids() {
        return this.guids;
    }

    /**
     * Get the finalIpAddresses property: The finalIpAddresses property.
     *
     * @return the finalIpAddresses value.
     */
    public List<ObservedString> getFinalIpAddresses() {
        return this.finalIpAddresses;
    }

    /**
     * Get the asns property: The asns property.
     *
     * @return the asns value.
     */
    public List<ObservedLong> getAsns() {
        return this.asns;
    }

    /**
     * Get the ipBlocks property: The ipBlocks property.
     *
     * @return the ipBlocks value.
     */
    public List<IpBlock> getIpBlocks() {
        return this.ipBlocks;
    }

    /**
     * Get the finalAsns property: The finalAsns property.
     *
     * @return the finalAsns value.
     */
    public List<ObservedLong> getFinalAsns() {
        return this.finalAsns;
    }

    /**
     * Get the finalIpBlocks property: The finalIpBlocks property.
     *
     * @return the finalIpBlocks value.
     */
    public List<IpBlock> getFinalIpBlocks() {
        return this.finalIpBlocks;
    }

    /**
     * Get the responseBodies property: The responseBodies property.
     *
     * @return the responseBodies value.
     */
    public List<ObservedString> getResponseBodies() {
        return this.responseBodies;
    }

    /**
     * Get the domainAsset property: The domainAsset property.
     *
     * @return the domainAsset value.
     */
    public DomainAsset getDomainAsset() {
        return this.domainAsset;
    }

    /**
     * Get the rootUrl property: The rootUrl property.
     *
     * @return the rootUrl value.
     */
    public ObservedBoolean getRootUrl() {
        return this.rootUrl;
    }

    /**
     * Get the isRootUrl property: The isRootUrl property.
     *
     * @return the isRootUrl value.
     */
    public Boolean isRootUrl() {
        return this.isRootUrl;
    }

    /**
     * Get the location property: The location property.
     *
     * @return the location value.
     */
    public List<ObservedLocation> getLocation() {
        return this.location;
    }

    /**
     * Get the services property: The services property.
     *
     * @return the services value.
     */
    public List<Service> getServices() {
        return this.services;
    }

    /**
     * Get the siteStatus property: The siteStatus property.
     *
     * @return the siteStatus value.
     */
    public String getSiteStatus() {
        return this.siteStatus;
    }

    /**
     * Get the cnames property: The cnames property.
     *
     * @return the cnames value.
     */
    public List<ObservedString> getCnames() {
        return this.cnames;
    }

    /**
     * Get the cdns property: The cdns property.
     *
     * @return the cdns value.
     */
    public List<ObservedString> getCdns() {
        return this.cdns;
    }

    /**
     * Get the host property: The host property.
     *
     * @return the host value.
     */
    public String getHost() {
        return this.host;
    }

    /**
     * Get the domain property: The domain property.
     *
     * @return the domain value.
     */
    public String getDomain() {
        return this.domain;
    }

    /**
     * Get the sslServerConfig property: The sslServerConfig property.
     *
     * @return the sslServerConfig value.
     */
    public List<SslServerConfig> getSslServerConfig() {
        return this.sslServerConfig;
    }

    /**
     * Get the gdprAssetSecurityPolicies property: The gdprAssetSecurityPolicies property.
     *
     * @return the gdprAssetSecurityPolicies value.
     */
    public List<AssetSecurityPolicy> getGdprAssetSecurityPolicies() {
        return this.gdprAssetSecurityPolicies;
    }

    /**
     * Get the ipv4 property: The ipv4 property.
     *
     * @return the ipv4 value.
     */
    public List<ObservedBoolean> getIpv4() {
        return this.ipv4;
    }

    /**
     * Get the ipv6 property: The ipv6 property.
     *
     * @return the ipv6 value.
     */
    public List<ObservedBoolean> getIpv6() {
        return this.ipv6;
    }
}
