// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** ReportAssetSummaryResponse. */
@Immutable
public final class ReportAssetSummaryResponse {
    /*
     * The collection of asset summaries.
     */
    @JsonProperty(value = "assetSummaries")
    private List<AssetSummaryResponse> assetSummaries;

    /** Creates an instance of ReportAssetSummaryResponse class. */
    private ReportAssetSummaryResponse() {}

    /**
     * Get the assetSummaries property: The collection of asset summaries.
     *
     * @return the assetSummaries value.
     */
    public List<AssetSummaryResponse> getAssetSummaries() {
        return this.assetSummaries;
    }
}
