// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** ReportBillableAssetSummaryResponse. */
@Immutable
public final class ReportBillableAssetSummaryResponse {
    /*
     * The assetSummaries property.
     */
    @JsonProperty(value = "assetSummaries")
    private List<ReportBillableAssetSnapshotResponse> assetSummaries;

    /** Creates an instance of ReportBillableAssetSummaryResponse class. */
    private ReportBillableAssetSummaryResponse() {}

    /**
     * Get the assetSummaries property: The assetSummaries property.
     *
     * @return the assetSummaries value.
     */
    public List<ReportBillableAssetSnapshotResponse> getAssetSummaries() {
        return this.assetSummaries;
    }
}
