// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;
import java.util.List;

/** ReportBillableAssetSnapshotResponse. */
@Immutable
public final class ReportBillableAssetSnapshotResponse {
    /*
     * The date these assets were billed on.
     */
    @JsonProperty(value = "date")
    private LocalDate date;

    /*
     * The total number of billable assets for this date.
     */
    @JsonProperty(value = "total")
    private Long total;

    /*
     * The breakdown of billable asset counts for each asset type.
     */
    @JsonProperty(value = "assetBreakdown")
    private List<ReportBillableAssetBreakdown> assetBreakdown;

    /** Creates an instance of ReportBillableAssetSnapshotResponse class. */
    private ReportBillableAssetSnapshotResponse() {}

    /**
     * Get the date property: The date these assets were billed on.
     *
     * @return the date value.
     */
    public LocalDate getDate() {
        return this.date;
    }

    /**
     * Get the total property: The total number of billable assets for this date.
     *
     * @return the total value.
     */
    public Long getTotal() {
        return this.total;
    }

    /**
     * Get the assetBreakdown property: The breakdown of billable asset counts for each asset type.
     *
     * @return the assetBreakdown value.
     */
    public List<ReportBillableAssetBreakdown> getAssetBreakdown() {
        return this.assetBreakdown;
    }
}
