// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** ReportAssetSnapshotExportRequest. */
@Fluent
public final class ReportAssetSnapshotExportRequest {
    /*
     * The metric to retrieve a snapshot for.
     */
    @JsonProperty(value = "metric")
    private String metric;

    /*
     * The filename of the exported file.
     */
    @JsonProperty(value = "fileName")
    private String fileName;

    /*
     * The columns to include in the export
     */
    @JsonProperty(value = "columns")
    private List<String> columns;

    /** Creates an instance of ReportAssetSnapshotExportRequest class. */
    public ReportAssetSnapshotExportRequest() {}

    /**
     * Get the metric property: The metric to retrieve a snapshot for.
     *
     * @return the metric value.
     */
    public String getMetric() {
        return this.metric;
    }

    /**
     * Set the metric property: The metric to retrieve a snapshot for.
     *
     * @param metric the metric value to set.
     * @return the ReportAssetSnapshotExportRequest object itself.
     */
    public ReportAssetSnapshotExportRequest setMetric(String metric) {
        this.metric = metric;
        return this;
    }

    /**
     * Get the fileName property: The filename of the exported file.
     *
     * @return the fileName value.
     */
    public String getFileName() {
        return this.fileName;
    }

    /**
     * Set the fileName property: The filename of the exported file.
     *
     * @param fileName the fileName value to set.
     * @return the ReportAssetSnapshotExportRequest object itself.
     */
    public ReportAssetSnapshotExportRequest setFileName(String fileName) {
        this.fileName = fileName;
        return this;
    }

    /**
     * Get the columns property: The columns to include in the export.
     *
     * @return the columns value.
     */
    public List<String> getColumns() {
        return this.columns;
    }

    /**
     * Set the columns property: The columns to include in the export.
     *
     * @param columns the columns value to set.
     * @return the ReportAssetSnapshotExportRequest object itself.
     */
    public ReportAssetSnapshotExportRequest setColumns(List<String> columns) {
        this.columns = columns;
        return this;
    }
}
