// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** ReportAssetSnapshotRequest. */
@Fluent
public final class ReportAssetSnapshotRequest {
    /*
     * The metric to retrieve a snapshot for.
     */
    @JsonProperty(value = "metric")
    private String metric;

    /*
     * The name of the label to retrieve a snapshot for.
     */
    @JsonProperty(value = "labelName")
    private String labelName;

    /*
     * The number of assets per page.
     */
    @JsonProperty(value = "size")
    private Integer size;

    /*
     * The page to retrieve.
     */
    @JsonProperty(value = "page")
    private Integer page;

    /** Creates an instance of ReportAssetSnapshotRequest class. */
    public ReportAssetSnapshotRequest() {}

    /**
     * Get the metric property: The metric to retrieve a snapshot for.
     *
     * @return the metric value.
     */
    public String getMetric() {
        return this.metric;
    }

    /**
     * Set the metric property: The metric to retrieve a snapshot for.
     *
     * @param metric the metric value to set.
     * @return the ReportAssetSnapshotRequest object itself.
     */
    public ReportAssetSnapshotRequest setMetric(String metric) {
        this.metric = metric;
        return this;
    }

    /**
     * Get the labelName property: The name of the label to retrieve a snapshot for.
     *
     * @return the labelName value.
     */
    public String getLabelName() {
        return this.labelName;
    }

    /**
     * Set the labelName property: The name of the label to retrieve a snapshot for.
     *
     * @param labelName the labelName value to set.
     * @return the ReportAssetSnapshotRequest object itself.
     */
    public ReportAssetSnapshotRequest setLabelName(String labelName) {
        this.labelName = labelName;
        return this;
    }

    /**
     * Get the size property: The number of assets per page.
     *
     * @return the size value.
     */
    public Integer getSize() {
        return this.size;
    }

    /**
     * Set the size property: The number of assets per page.
     *
     * @param size the size value to set.
     * @return the ReportAssetSnapshotRequest object itself.
     */
    public ReportAssetSnapshotRequest setSize(Integer size) {
        this.size = size;
        return this;
    }

    /**
     * Get the page property: The page to retrieve.
     *
     * @return the page value.
     */
    public Integer getPage() {
        return this.page;
    }

    /**
     * Set the page property: The page to retrieve.
     *
     * @param page the page value to set.
     * @return the ReportAssetSnapshotRequest object itself.
     */
    public ReportAssetSnapshotRequest setPage(Integer page) {
        this.page = page;
        return this;
    }
}
