// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** ReportAssetSnapshotResponse. */
@Immutable
public final class ReportAssetSnapshotResponse {
    /*
     * The name of the metric.
     */
    @JsonProperty(value = "displayName")
    private String displayName;

    /*
     * The unique metric name.
     */
    @JsonProperty(value = "metric")
    private String metric;

    /*
     * The customer label that was filtered on, if one was provided.
     */
    @JsonProperty(value = "labelName")
    private String labelName;

    /*
     * The last time this asset data was updated on this metric.
     */
    @JsonProperty(value = "updatedAt")
    private OffsetDateTime updatedAt;

    /*
     * A description of what the metric represents.
     */
    @JsonProperty(value = "description")
    private String description;

    /*
     * The assets property.
     */
    @JsonProperty(value = "assets", required = true)
    private AssetPageResponse assets;

    /**
     * Creates an instance of ReportAssetSnapshotResponse class.
     *
     * @param assets the assets value to set.
     */
    @JsonCreator
    private ReportAssetSnapshotResponse(@JsonProperty(value = "assets", required = true) AssetPageResponse assets) {
        this.assets = assets;
    }

    /**
     * Get the displayName property: The name of the metric.
     *
     * @return the displayName value.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Get the metric property: The unique metric name.
     *
     * @return the metric value.
     */
    public String getMetric() {
        return this.metric;
    }

    /**
     * Get the labelName property: The customer label that was filtered on, if one was provided.
     *
     * @return the labelName value.
     */
    public String getLabelName() {
        return this.labelName;
    }

    /**
     * Get the updatedAt property: The last time this asset data was updated on this metric.
     *
     * @return the updatedAt value.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Get the description property: A description of what the metric represents.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Get the assets property: The assets property.
     *
     * @return the assets value.
     */
    public AssetPageResponse getAssets() {
        return this.assets;
    }
}
