// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/** ReportBillableAssetBreakdown. */
@Immutable
public final class ReportBillableAssetBreakdown {
    /*
     * The kind of billable asset.
     */
    @JsonProperty(value = "kind")
    private ReportBillableAssetBreakdownKind kind;

    /*
     * The number of assets of this type.
     */
    @JsonProperty(value = "count")
    private Long count;

    /** Creates an instance of ReportBillableAssetBreakdown class. */
    private ReportBillableAssetBreakdown() {}

    /**
     * Get the kind property: The kind of billable asset.
     *
     * @return the kind value.
     */
    public ReportBillableAssetBreakdownKind getKind() {
        return this.kind;
    }

    /**
     * Get the count property: The number of assets of this type.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }
}
