// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** Reputation. */
@Immutable
public final class Reputation {
    /*
     * The listName property.
     */
    @JsonProperty(value = "listName")
    private String listName;

    /*
     * The threatType property.
     */
    @JsonProperty(value = "threatType")
    private String threatType;

    /*
     * The trusted property.
     */
    @JsonProperty(value = "trusted")
    private Boolean trusted;

    /*
     * The cidr property.
     */
    @JsonProperty(value = "cidr")
    private String cidr;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The listUpdatedAt property.
     */
    @JsonProperty(value = "listUpdatedAt")
    private OffsetDateTime listUpdatedAt;

    /*
     * The recent property.
     */
    @JsonProperty(value = "recent")
    private Boolean recent;

    /** Creates an instance of Reputation class. */
    private Reputation() {}

    /**
     * Get the listName property: The listName property.
     *
     * @return the listName value.
     */
    public String getListName() {
        return this.listName;
    }

    /**
     * Get the threatType property: The threatType property.
     *
     * @return the threatType value.
     */
    public String getThreatType() {
        return this.threatType;
    }

    /**
     * Get the trusted property: The trusted property.
     *
     * @return the trusted value.
     */
    public Boolean isTrusted() {
        return this.trusted;
    }

    /**
     * Get the cidr property: The cidr property.
     *
     * @return the cidr value.
     */
    public String getCidr() {
        return this.cidr;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the listUpdatedAt property: The listUpdatedAt property.
     *
     * @return the listUpdatedAt value.
     */
    public OffsetDateTime getListUpdatedAt() {
        return this.listUpdatedAt;
    }

    /**
     * Get the recent property: The recent property.
     *
     * @return the recent value.
     */
    public Boolean isRecent() {
        return this.recent;
    }
}
