// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** SavedFilterRequest. */
@Immutable
public final class SavedFilterRequest {
    /*
     * An expression on the resource type that selects the resources to be returned.
     */
    @JsonProperty(value = "filter", required = true)
    private String filter;

    /*
     * A human readable description of the saved filter.
     */
    @JsonProperty(value = "description", required = true)
    private String description;

    /**
     * Creates an instance of SavedFilterRequest class.
     *
     * @param filter the filter value to set.
     * @param description the description value to set.
     */
    @JsonCreator
    public SavedFilterRequest(
            @JsonProperty(value = "filter", required = true) String filter,
            @JsonProperty(value = "description", required = true) String description) {
        this.filter = filter;
        this.description = description;
    }

    /**
     * Get the filter property: An expression on the resource type that selects the resources to be returned.
     *
     * @return the filter value.
     */
    public String getFilter() {
        return this.filter;
    }

    /**
     * Get the description property: A human readable description of the saved filter.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }
}
