// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** ScanMetadata. */
@Immutable
public final class ScanMetadata {
    /*
     * The port property.
     */
    @JsonProperty(value = "port")
    private Integer port;

    /*
     * The bannerMetadata property.
     */
    @JsonProperty(value = "bannerMetadata")
    private String bannerMetadata;

    /*
     * The startScan property.
     */
    @JsonProperty(value = "startScan")
    private OffsetDateTime startScan;

    /*
     * The endScan property.
     */
    @JsonProperty(value = "endScan")
    private OffsetDateTime endScan;

    /** Creates an instance of ScanMetadata class. */
    private ScanMetadata() {}

    /**
     * Get the port property: The port property.
     *
     * @return the port value.
     */
    public Integer getPort() {
        return this.port;
    }

    /**
     * Get the bannerMetadata property: The bannerMetadata property.
     *
     * @return the bannerMetadata value.
     */
    public String getBannerMetadata() {
        return this.bannerMetadata;
    }

    /**
     * Get the startScan property: The startScan property.
     *
     * @return the startScan value.
     */
    public OffsetDateTime getStartScan() {
        return this.startScan;
    }

    /**
     * Get the endScan property: The endScan property.
     *
     * @return the endScan value.
     */
    public OffsetDateTime getEndScan() {
        return this.endScan;
    }
}
