// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** Service. */
@Immutable
public final class Service {
    /*
     * The scheme property.
     */
    @JsonProperty(value = "scheme")
    private String scheme;

    /*
     * The port property.
     */
    @JsonProperty(value = "port")
    private Integer port;

    /*
     * The webComponents property.
     */
    @JsonProperty(value = "webComponents")
    private List<WebComponent> webComponents;

    /*
     * The sslCerts property.
     */
    @JsonProperty(value = "sslCerts")
    private List<SslCertAsset> sslCerts;

    /*
     * The exceptions property.
     */
    @JsonProperty(value = "exceptions")
    private List<ObservedString> exceptions;

    /*
     * The sources property.
     */
    @JsonProperty(value = "sources")
    private List<Source> sources;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The recent property.
     */
    @JsonProperty(value = "recent")
    private Boolean recent;

    /*
     * The portStates property.
     */
    @JsonProperty(value = "portStates")
    private List<ObservedPortState> portStates;

    /** Creates an instance of Service class. */
    private Service() {}

    /**
     * Get the scheme property: The scheme property.
     *
     * @return the scheme value.
     */
    public String getScheme() {
        return this.scheme;
    }

    /**
     * Get the port property: The port property.
     *
     * @return the port value.
     */
    public Integer getPort() {
        return this.port;
    }

    /**
     * Get the webComponents property: The webComponents property.
     *
     * @return the webComponents value.
     */
    public List<WebComponent> getWebComponents() {
        return this.webComponents;
    }

    /**
     * Get the sslCerts property: The sslCerts property.
     *
     * @return the sslCerts value.
     */
    public List<SslCertAsset> getSslCerts() {
        return this.sslCerts;
    }

    /**
     * Get the exceptions property: The exceptions property.
     *
     * @return the exceptions value.
     */
    public List<ObservedString> getExceptions() {
        return this.exceptions;
    }

    /**
     * Get the sources property: The sources property.
     *
     * @return the sources value.
     */
    public List<Source> getSources() {
        return this.sources;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the recent property: The recent property.
     *
     * @return the recent value.
     */
    public Boolean isRecent() {
        return this.recent;
    }

    /**
     * Get the portStates property: The portStates property.
     *
     * @return the portStates value.
     */
    public List<ObservedPortState> getPortStates() {
        return this.portStates;
    }
}
