// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** SoaRecord. */
@Immutable
public final class SoaRecord {
    /*
     * The nameServer property.
     */
    @JsonProperty(value = "nameServer")
    private String nameServer;

    /*
     * The email property.
     */
    @JsonProperty(value = "email")
    private String email;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The serialNumber property.
     */
    @JsonProperty(value = "serialNumber")
    private Long serialNumber;

    /*
     * The recent property.
     */
    @JsonProperty(value = "recent")
    private Boolean recent;

    /** Creates an instance of SoaRecord class. */
    private SoaRecord() {}

    /**
     * Get the nameServer property: The nameServer property.
     *
     * @return the nameServer value.
     */
    public String getNameServer() {
        return this.nameServer;
    }

    /**
     * Get the email property: The email property.
     *
     * @return the email value.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the serialNumber property: The serialNumber property.
     *
     * @return the serialNumber value.
     */
    public Long getSerialNumber() {
        return this.serialNumber;
    }

    /**
     * Get the recent property: The recent property.
     *
     * @return the recent value.
     */
    public Boolean isRecent() {
        return this.recent;
    }
}
