// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The SslCertAssetResponse model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("sslCert")
@Immutable
public final class SslCertAssetResponse extends AssetResponse {
    /*
     * The asset property.
     */
    @JsonProperty(value = "asset", required = true)
    private SslCertAsset asset;

    /**
     * Creates an instance of SslCertAssetResponse class.
     *
     * @param asset the asset value to set.
     * @param asset the asset value to set.
     */
    @JsonCreator
    private SslCertAssetResponse(
            @JsonProperty(value = "asset", required = true) Object asset,
            @JsonProperty(value = "asset", required = true) SslCertAsset asset) {
        super(asset);
        this.asset = asset;
    }

    /**
     * Get the asset property: The asset property.
     *
     * @return the asset value.
     */
    public SslCertAsset getAsset() {
        return this.asset;
    }
}
