// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** SslCertAsset. */
@Immutable
public final class SslCertAsset {
    /*
     * The sha1 property.
     */
    @JsonProperty(value = "sha1")
    private String sha1;

    /*
     * The subjectCommonNames property.
     */
    @JsonProperty(value = "subjectCommonNames")
    private List<String> subjectCommonNames;

    /*
     * The organizations property.
     */
    @JsonProperty(value = "organizations")
    private List<String> organizations;

    /*
     * The organizationalUnits property.
     */
    @JsonProperty(value = "organizationalUnits")
    private List<String> organizationalUnits;

    /*
     * The issuerCommonNames property.
     */
    @JsonProperty(value = "issuerCommonNames")
    private List<String> issuerCommonNames;

    /*
     * The sigAlgName property.
     */
    @JsonProperty(value = "sigAlgName")
    private String sigAlgName;

    /*
     * The invalidAfter property.
     */
    @JsonProperty(value = "invalidAfter")
    private OffsetDateTime invalidAfter;

    /*
     * The serialNumber property.
     */
    @JsonProperty(value = "serialNumber")
    private String serialNumber;

    /*
     * The subjectAlternativeNames property.
     */
    @JsonProperty(value = "subjectAlternativeNames")
    private List<String> subjectAlternativeNames;

    /*
     * The issuerAlternativeNames property.
     */
    @JsonProperty(value = "issuerAlternativeNames")
    private List<String> issuerAlternativeNames;

    /*
     * The sources property.
     */
    @JsonProperty(value = "sources")
    private List<Source> sources;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The invalidBefore property.
     */
    @JsonProperty(value = "invalidBefore")
    private OffsetDateTime invalidBefore;

    /*
     * The keySize property.
     */
    @JsonProperty(value = "keySize")
    private Integer keySize;

    /*
     * The keyAlgorithm property.
     */
    @JsonProperty(value = "keyAlgorithm")
    private String keyAlgorithm;

    /*
     * The subjectLocality property.
     */
    @JsonProperty(value = "subjectLocality")
    private List<String> subjectLocality;

    /*
     * The subjectState property.
     */
    @JsonProperty(value = "subjectState")
    private List<String> subjectState;

    /*
     * The subjectCountry property.
     */
    @JsonProperty(value = "subjectCountry")
    private List<String> subjectCountry;

    /*
     * The issuerLocality property.
     */
    @JsonProperty(value = "issuerLocality")
    private List<String> issuerLocality;

    /*
     * The issuerState property.
     */
    @JsonProperty(value = "issuerState")
    private List<String> issuerState;

    /*
     * The issuerCountry property.
     */
    @JsonProperty(value = "issuerCountry")
    private List<String> issuerCountry;

    /*
     * The subjectOrganizations property.
     */
    @JsonProperty(value = "subjectOrganizations")
    private List<String> subjectOrganizations;

    /*
     * The subjectOrganizationalUnits property.
     */
    @JsonProperty(value = "subjectOrganizationalUnits")
    private List<String> subjectOrganizationalUnits;

    /*
     * The issuerOrganizations property.
     */
    @JsonProperty(value = "issuerOrganizations")
    private List<String> issuerOrganizations;

    /*
     * The issuerOrganizationalUnits property.
     */
    @JsonProperty(value = "issuerOrganizationalUnits")
    private List<String> issuerOrganizationalUnits;

    /*
     * The version property.
     */
    @JsonProperty(value = "version")
    private Integer version;

    /*
     * The certificateAuthority property.
     */
    @JsonProperty(value = "certificateAuthority")
    private Boolean certificateAuthority;

    /*
     * The selfSigned property.
     */
    @JsonProperty(value = "selfSigned")
    private Boolean selfSigned;

    /*
     * The sigAlgOid property.
     */
    @JsonProperty(value = "sigAlgOid")
    private String sigAlgOid;

    /*
     * The recent property.
     */
    @JsonProperty(value = "recent")
    private Boolean recent;

    /*
     * The validationType property.
     */
    @JsonProperty(value = "validationType")
    private SslCertAssetValidationType validationType;

    /** Creates an instance of SslCertAsset class. */
    private SslCertAsset() {}

    /**
     * Get the sha1 property: The sha1 property.
     *
     * @return the sha1 value.
     */
    public String getSha1() {
        return this.sha1;
    }

    /**
     * Get the subjectCommonNames property: The subjectCommonNames property.
     *
     * @return the subjectCommonNames value.
     */
    public List<String> getSubjectCommonNames() {
        return this.subjectCommonNames;
    }

    /**
     * Get the organizations property: The organizations property.
     *
     * @return the organizations value.
     */
    public List<String> getOrganizations() {
        return this.organizations;
    }

    /**
     * Get the organizationalUnits property: The organizationalUnits property.
     *
     * @return the organizationalUnits value.
     */
    public List<String> getOrganizationalUnits() {
        return this.organizationalUnits;
    }

    /**
     * Get the issuerCommonNames property: The issuerCommonNames property.
     *
     * @return the issuerCommonNames value.
     */
    public List<String> getIssuerCommonNames() {
        return this.issuerCommonNames;
    }

    /**
     * Get the sigAlgName property: The sigAlgName property.
     *
     * @return the sigAlgName value.
     */
    public String getSigAlgName() {
        return this.sigAlgName;
    }

    /**
     * Get the invalidAfter property: The invalidAfter property.
     *
     * @return the invalidAfter value.
     */
    public OffsetDateTime getInvalidAfter() {
        return this.invalidAfter;
    }

    /**
     * Get the serialNumber property: The serialNumber property.
     *
     * @return the serialNumber value.
     */
    public String getSerialNumber() {
        return this.serialNumber;
    }

    /**
     * Get the subjectAlternativeNames property: The subjectAlternativeNames property.
     *
     * @return the subjectAlternativeNames value.
     */
    public List<String> getSubjectAlternativeNames() {
        return this.subjectAlternativeNames;
    }

    /**
     * Get the issuerAlternativeNames property: The issuerAlternativeNames property.
     *
     * @return the issuerAlternativeNames value.
     */
    public List<String> getIssuerAlternativeNames() {
        return this.issuerAlternativeNames;
    }

    /**
     * Get the sources property: The sources property.
     *
     * @return the sources value.
     */
    public List<Source> getSources() {
        return this.sources;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the invalidBefore property: The invalidBefore property.
     *
     * @return the invalidBefore value.
     */
    public OffsetDateTime getInvalidBefore() {
        return this.invalidBefore;
    }

    /**
     * Get the keySize property: The keySize property.
     *
     * @return the keySize value.
     */
    public Integer getKeySize() {
        return this.keySize;
    }

    /**
     * Get the keyAlgorithm property: The keyAlgorithm property.
     *
     * @return the keyAlgorithm value.
     */
    public String getKeyAlgorithm() {
        return this.keyAlgorithm;
    }

    /**
     * Get the subjectLocality property: The subjectLocality property.
     *
     * @return the subjectLocality value.
     */
    public List<String> getSubjectLocality() {
        return this.subjectLocality;
    }

    /**
     * Get the subjectState property: The subjectState property.
     *
     * @return the subjectState value.
     */
    public List<String> getSubjectState() {
        return this.subjectState;
    }

    /**
     * Get the subjectCountry property: The subjectCountry property.
     *
     * @return the subjectCountry value.
     */
    public List<String> getSubjectCountry() {
        return this.subjectCountry;
    }

    /**
     * Get the issuerLocality property: The issuerLocality property.
     *
     * @return the issuerLocality value.
     */
    public List<String> getIssuerLocality() {
        return this.issuerLocality;
    }

    /**
     * Get the issuerState property: The issuerState property.
     *
     * @return the issuerState value.
     */
    public List<String> getIssuerState() {
        return this.issuerState;
    }

    /**
     * Get the issuerCountry property: The issuerCountry property.
     *
     * @return the issuerCountry value.
     */
    public List<String> getIssuerCountry() {
        return this.issuerCountry;
    }

    /**
     * Get the subjectOrganizations property: The subjectOrganizations property.
     *
     * @return the subjectOrganizations value.
     */
    public List<String> getSubjectOrganizations() {
        return this.subjectOrganizations;
    }

    /**
     * Get the subjectOrganizationalUnits property: The subjectOrganizationalUnits property.
     *
     * @return the subjectOrganizationalUnits value.
     */
    public List<String> getSubjectOrganizationalUnits() {
        return this.subjectOrganizationalUnits;
    }

    /**
     * Get the issuerOrganizations property: The issuerOrganizations property.
     *
     * @return the issuerOrganizations value.
     */
    public List<String> getIssuerOrganizations() {
        return this.issuerOrganizations;
    }

    /**
     * Get the issuerOrganizationalUnits property: The issuerOrganizationalUnits property.
     *
     * @return the issuerOrganizationalUnits value.
     */
    public List<String> getIssuerOrganizationalUnits() {
        return this.issuerOrganizationalUnits;
    }

    /**
     * Get the version property: The version property.
     *
     * @return the version value.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Get the certificateAuthority property: The certificateAuthority property.
     *
     * @return the certificateAuthority value.
     */
    public Boolean isCertificateAuthority() {
        return this.certificateAuthority;
    }

    /**
     * Get the selfSigned property: The selfSigned property.
     *
     * @return the selfSigned value.
     */
    public Boolean isSelfSigned() {
        return this.selfSigned;
    }

    /**
     * Get the sigAlgOid property: The sigAlgOid property.
     *
     * @return the sigAlgOid value.
     */
    public String getSigAlgOid() {
        return this.sigAlgOid;
    }

    /**
     * Get the recent property: The recent property.
     *
     * @return the recent value.
     */
    public Boolean isRecent() {
        return this.recent;
    }

    /**
     * Get the validationType property: The validationType property.
     *
     * @return the validationType value.
     */
    public SslCertAssetValidationType getValidationType() {
        return this.validationType;
    }
}
