// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** SslServerConfig. */
@Immutable
public final class SslServerConfig {
    /*
     * The tlsVersions property.
     */
    @JsonProperty(value = "tlsVersions")
    private List<String> tlsVersions;

    /*
     * The cipherSuites property.
     */
    @JsonProperty(value = "cipherSuites")
    private List<String> cipherSuites;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The sources property.
     */
    @JsonProperty(value = "sources")
    private List<Source> sources;

    /** Creates an instance of SslServerConfig class. */
    private SslServerConfig() {}

    /**
     * Get the tlsVersions property: The tlsVersions property.
     *
     * @return the tlsVersions value.
     */
    public List<String> getTlsVersions() {
        return this.tlsVersions;
    }

    /**
     * Get the cipherSuites property: The cipherSuites property.
     *
     * @return the cipherSuites value.
     */
    public List<String> getCipherSuites() {
        return this.cipherSuites;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the sources property: The sources property.
     *
     * @return the sources value.
     */
    public List<Source> getSources() {
        return this.sources;
    }
}
