// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** SubResourceIntegrityCheck. */
@Immutable
public final class SubResourceIntegrityCheck {
    /*
     * The violation property.
     */
    @JsonProperty(value = "violation")
    private Boolean violation;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The causePageUrl property.
     */
    @JsonProperty(value = "causePageUrl")
    private String causePageUrl;

    /*
     * The crawlGuid property.
     */
    @JsonProperty(value = "crawlGuid")
    private String crawlGuid;

    /*
     * The pageGuid property.
     */
    @JsonProperty(value = "pageGuid")
    private String pageGuid;

    /*
     * The resourceGuid property.
     */
    @JsonProperty(value = "resourceGuid")
    private String resourceGuid;

    /*
     * The expectedHash property.
     */
    @JsonProperty(value = "expectedHash")
    private String expectedHash;

    /** Creates an instance of SubResourceIntegrityCheck class. */
    private SubResourceIntegrityCheck() {}

    /**
     * Get the violation property: The violation property.
     *
     * @return the violation value.
     */
    public Boolean isViolation() {
        return this.violation;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the causePageUrl property: The causePageUrl property.
     *
     * @return the causePageUrl value.
     */
    public String getCausePageUrl() {
        return this.causePageUrl;
    }

    /**
     * Get the crawlGuid property: The crawlGuid property.
     *
     * @return the crawlGuid value.
     */
    public String getCrawlGuid() {
        return this.crawlGuid;
    }

    /**
     * Get the pageGuid property: The pageGuid property.
     *
     * @return the pageGuid value.
     */
    public String getPageGuid() {
        return this.pageGuid;
    }

    /**
     * Get the resourceGuid property: The resourceGuid property.
     *
     * @return the resourceGuid value.
     */
    public String getResourceGuid() {
        return this.resourceGuid;
    }

    /**
     * Get the expectedHash property: The expectedHash property.
     *
     * @return the expectedHash value.
     */
    public String getExpectedHash() {
        return this.expectedHash;
    }
}
