// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for TaskPhase. */
public final class TaskPhase extends ExpandableStringEnum<TaskPhase> {
    /** Static value running for TaskPhase. */
    public static final TaskPhase RUNNING = fromString("running");

    /** Static value polling for TaskPhase. */
    public static final TaskPhase POLLING = fromString("polling");

    /** Static value complete for TaskPhase. */
    public static final TaskPhase COMPLETE = fromString("complete");

    /**
     * Creates a new instance of TaskPhase value.
     *
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public TaskPhase() {}

    /**
     * Creates or finds a TaskPhase from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding TaskPhase.
     */
    @JsonCreator
    public static TaskPhase fromString(String name) {
        return fromString(name, TaskPhase.class);
    }

    /**
     * Gets known TaskPhase values.
     *
     * @return known TaskPhase values.
     */
    public static Collection<TaskPhase> values() {
        return values(TaskPhase.class);
    }
}
