// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for TaskState. */
public final class TaskState extends ExpandableStringEnum<TaskState> {
    /** Static value pending for TaskState. */
    public static final TaskState PENDING = fromString("pending");

    /** Static value running for TaskState. */
    public static final TaskState RUNNING = fromString("running");

    /** Static value paused for TaskState. */
    public static final TaskState PAUSED = fromString("paused");

    /** Static value complete for TaskState. */
    public static final TaskState COMPLETE = fromString("complete");

    /** Static value incomplete for TaskState. */
    public static final TaskState INCOMPLETE = fromString("incomplete");

    /** Static value failed for TaskState. */
    public static final TaskState FAILED = fromString("failed");

    /** Static value warning for TaskState. */
    public static final TaskState WARNING = fromString("warning");

    /**
     * Creates a new instance of TaskState value.
     *
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public TaskState() {}

    /**
     * Creates or finds a TaskState from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding TaskState.
     */
    @JsonCreator
    public static TaskState fromString(String name) {
        return fromString(name, TaskState.class);
    }

    /**
     * Gets known TaskState values.
     *
     * @return known TaskState values.
     */
    public static Collection<TaskState> values() {
        return values(TaskState.class);
    }
}
