// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** TaskResponse. */
@Immutable
public final class TaskResponse {
    /*
     * The unique identifier of the task.
     */
    @JsonProperty(value = "id")
    private String id;

    /*
     * The time the task started.
     */
    @JsonProperty(value = "startedAt")
    private OffsetDateTime startedAt;

    /*
     * The time the task completed.
     */
    @JsonProperty(value = "completedAt")
    private OffsetDateTime completedAt;

    /*
     * The last time the status of the task was updated.
     */
    @JsonProperty(value = "lastPolledAt")
    private OffsetDateTime lastPolledAt;

    /*
     * The state the task is in.
     */
    @JsonProperty(value = "state")
    private TaskState state;

    /*
     * The phase the task is in.
     */
    @JsonProperty(value = "phase")
    private TaskPhase phase;

    /*
     * The reason the task was moved into its current state, if the task wasn't completed.
     */
    @JsonProperty(value = "reason")
    private String reason;

    /*
     * Attributes unique to the task.  This differs by task type.
     */
    @JsonProperty(value = "metadata")
    private Object metadata;

    /** Creates an instance of TaskResponse class. */
    private TaskResponse() {}

    /**
     * Get the id property: The unique identifier of the task.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Get the startedAt property: The time the task started.
     *
     * @return the startedAt value.
     */
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Get the completedAt property: The time the task completed.
     *
     * @return the completedAt value.
     */
    public OffsetDateTime getCompletedAt() {
        return this.completedAt;
    }

    /**
     * Get the lastPolledAt property: The last time the status of the task was updated.
     *
     * @return the lastPolledAt value.
     */
    public OffsetDateTime getLastPolledAt() {
        return this.lastPolledAt;
    }

    /**
     * Get the state property: The state the task is in.
     *
     * @return the state value.
     */
    public TaskState getState() {
        return this.state;
    }

    /**
     * Get the phase property: The phase the task is in.
     *
     * @return the phase value.
     */
    public TaskPhase getPhase() {
        return this.phase;
    }

    /**
     * Get the reason property: The reason the task was moved into its current state, if the task wasn't completed.
     *
     * @return the reason value.
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * Get the metadata property: Attributes unique to the task. This differs by task type.
     *
     * @return the metadata value.
     */
    public Object getMetadata() {
        return this.metadata;
    }
}
