// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** ValidateResponse. */
@Immutable
public final class ValidateResponse {
    /*
     * The error property.
     */
    @JsonProperty(value = "error", required = true)
    private ErrorDetail error;

    /**
     * Creates an instance of ValidateResponse class.
     *
     * @param error the error value to set.
     */
    @JsonCreator
    private ValidateResponse(@JsonProperty(value = "error", required = true) ErrorDetail error) {
        this.error = error;
    }

    /**
     * Get the error property: The error property.
     *
     * @return the error value.
     */
    public ErrorDetail getError() {
        return this.error;
    }
}
