// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** WebComponent. */
@Immutable
public final class WebComponent {
    /*
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * The type property.
     */
    @JsonProperty(value = "type")
    private String type;

    /*
     * The version property.
     */
    @JsonProperty(value = "version")
    private String version;

    /*
     * The ruleId property.
     */
    @JsonProperty(value = "ruleId")
    private List<String> ruleId;

    /*
     * The firstSeen property.
     */
    @JsonProperty(value = "firstSeen")
    private OffsetDateTime firstSeen;

    /*
     * The lastSeen property.
     */
    @JsonProperty(value = "lastSeen")
    private OffsetDateTime lastSeen;

    /*
     * The count property.
     */
    @JsonProperty(value = "count")
    private Long count;

    /*
     * The cve property.
     */
    @JsonProperty(value = "cve")
    private List<Cve> cve;

    /*
     * The endOfLife property.
     */
    @JsonProperty(value = "endOfLife")
    private Long endOfLife;

    /*
     * The recent property.
     */
    @JsonProperty(value = "recent")
    private Boolean recent;

    /*
     * The ports property.
     */
    @JsonProperty(value = "ports")
    private List<Port> ports;

    /*
     * The sources property.
     */
    @JsonProperty(value = "sources")
    private List<Source> sources;

    /*
     * The service property.
     */
    @JsonProperty(value = "service")
    private String service;

    /** Creates an instance of WebComponent class. */
    private WebComponent() {}

    /**
     * Get the name property: The name property.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Get the type property: The type property.
     *
     * @return the type value.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Get the version property: The version property.
     *
     * @return the version value.
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * Get the ruleId property: The ruleId property.
     *
     * @return the ruleId value.
     */
    public List<String> getRuleId() {
        return this.ruleId;
    }

    /**
     * Get the firstSeen property: The firstSeen property.
     *
     * @return the firstSeen value.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    /**
     * Get the lastSeen property: The lastSeen property.
     *
     * @return the lastSeen value.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    /**
     * Get the count property: The count property.
     *
     * @return the count value.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Get the cve property: The cve property.
     *
     * @return the cve value.
     */
    public List<Cve> getCve() {
        return this.cve;
    }

    /**
     * Get the endOfLife property: The endOfLife property.
     *
     * @return the endOfLife value.
     */
    public Long getEndOfLife() {
        return this.endOfLife;
    }

    /**
     * Get the recent property: The recent property.
     *
     * @return the recent value.
     */
    public Boolean isRecent() {
        return this.recent;
    }

    /**
     * Get the ports property: The ports property.
     *
     * @return the ports value.
     */
    public List<Port> getPorts() {
        return this.ports;
    }

    /**
     * Get the sources property: The sources property.
     *
     * @return the sources value.
     */
    public List<Source> getSources() {
        return this.sources;
    }

    /**
     * Get the service property: The service property.
     *
     * @return the service value.
     */
    public String getService() {
        return this.service;
    }
}
