// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.easm;

import com.azure.core.util.ServiceVersion;

/** Service version of EASMClient. */
public enum EASMServiceVersion implements ServiceVersion {
    /** Enum value 2023-03-01-preview. */
    V2023_03_01_PREVIEW("2023-03-01-preview");

    private final String version;

    EASMServiceVersion(String version) {
        this.version = version;
    }

    /** {@inheritDoc} */
    @Override
    public String getVersion() {
        return this.version;
    }

    /**
     * Gets the latest service version supported by this client library.
     *
     * @return The latest {@link EASMServiceVersion}.
     */
    public static EASMServiceVersion getLatest() {
        return V2023_03_01_PREVIEW;
    }
}
