parameters:
  "python-sdk-folder":
    default: "{cwd}/azure-sdk-for-python/"
  "service-directory-name":
    default: "easm"

emit: [
  "@azure-tools/typespec-python",
  "@azure-tools/typespec-java"
]

options:
  "@azure-tools/typespec-python":
    "package-mode": "dataplane"
    "package-name": "azure-defender-easm"
    "emitter-output-dir": "{python-sdk-folder}/sdk/{service-directory-name}/{package-name}"
